### ISSUE TITLE
Catch errors from git being absent and continue on as best possible

### ISSUE THREAD

**Issue by mitchellhamilton** [atlassian/changesets#102]
We'll need to handle these two cases in our usages of git:
- The `git` command doesn't exist
- There isn't a git repo

**Comment by ajaymathur** [comment]
Hey @mitchellhamilton ,

We are expecting to create a uncommitted Changeset and log error?
or log error and do nothing else?

I believe same flow will apply to both?

I can take this up.  

Thanks 🙂

**Comment by mitchellhamilton** [comment]
By the time we're committing, we've already written the changeset so leaving it uncommitted is probably the best thing to do. We probably don't even have to handle the two cases I mentioned specially, checking if git's exit code is non-zero, logging the stderr along with a message says that changesets couldn't do the thing and exiting with a non-zero code is probably fine. For `getChangedPackagesSinceMaster` though, we shouldn't exit with a non-zero code or log anything if git fails and instead return an empty array.

There's a lot of restructuring in #139 so if you could base your changes from that branch, that would be great.

Thanks for doing this!

**Comment by mitchellhamilton** [comment]
Fixed by #173
