### ISSUE TITLE
Improve messages in bolt-check

### ISSUE THREAD

**Issue by mitchellhamilton** [atlassian/changesets#112]

**Comment by Noviny** [comment]
Big one is I believe, when bolt-check is successful alter the message so doing it in postinstall is less confusing/weird.

**Comment by mitchellhamilton** [comment]
Another big one is the "run bolt-check --fix to fix this" message. Just saw someone see the output of bolt-check because of a postinstall hook and they were unsure of what to do to fix it.

**Comment by Noviny** [comment]
Closing this, as our recommendation is now to use [manypkg](https://github.com/thinkmill/manypkg) instead, so we aren't planning on working on this.
