### ISSUE TITLE
Rename bolt-check

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#120]
Bolt check, and 'enforce bolt's constraints' have been really useful mnemnonics, but as this looks like it's getting picked up for wider use/we have been encouraging people unfamiliar with bolt to use it, it's leading to more and more confusion.

We need to:

- rename it to not reference bolt
- write the docs to describe what it does without referencing bolt

**Comment by mitchellhamilton** [comment]
Another important thing: explain **why** it does what it does and why people would want these constraints.

**Comment by Noviny** [comment]
@mitchellhamilton closing this with the assumption we'll just recommend replacing bolt-check with manypkg in the future.
