### ISSUE TITLE
1.3.0 seems to ask for OTP in CI

### ISSUE THREAD

**Issue by lukebatchelor** [atlassian/changesets#127]
Version 1.3.0 seems to be making changesets ask for OTP, even in CI, even when 2FA is not enabled.

https://bitbucket.org/atlassian/atlaskit-mk-2/addon/pipelines/home#!/results/67941

**Comment by mitchellhamilton** [comment]
@Noviny is on holiday right now so it'll probably be a couple weeks until there's another release but if you want a quick fix, you can pass the otp flag with any number, e.g. `yarn changeset release --otp=1`
