### ISSUE TITLE
Sort the heck out of logger

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#142]
I reckon the thing to do is:

a) make `@changesets/logger` - I want to make a point of consistency, and be able to silence logging easily in testing
b) write out rules around how to do this.

I'm not super opinionated about this, apart from we should have consistency and make it easy to silence in tests.

**Comment by ajaymathur** [comment]
Hey @Noviny , I would like to take a stab on it. Also, I closed an issues basically which was to move all the messages to a common place with each being function call. Do you think that will be helpful too?

**Comment by Noviny** [comment]
I'd be super keen to see you take a stab of it.

**Comment by Noviny** [comment]
Mostly centralising error messages is to make sure different packages needing to throw the same kinds of errors etc all actually presented the same.

**Comment by ajaymathur** [comment]
Closing this since https://github.com/atlassian/changesets/pull/182 got merged. Error should be part of seperate issue if required. 🙂
