### ISSUE TITLE
Make github changesets entries not thank core maintainers

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#161]
Iunno, maybe this is just be being weird, but having "Thanks @noviny" in a bunch of changelog stuff for the thing it's my responsibility to maintain/look after is weird to me.

@mitchellhamilton do you have any thought opinions about this?

**Comment by mitchellhamilton** [comment]
Yeah, I do think it's a bit weird but also, I don't feel that strongly about it either way. I guess the question is, what are the alternatives? Remove the thanks? Have a list of who is a core maintainer?

**Comment by Noviny** [comment]
I'd like a core maintainer list to use to strip the thanks for those people.

Going to close this as an issue though just because it's so far down the priority line.

May reopen later/change this if it really bothers me.

**Comment by wottpal** [comment]
Did anyone take the extra mile here and set up a custom formatter like that?
