### ISSUE TITLE
Update sinceMaster flag to allow setting branches

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#191]
## Problem

If you are running releases off a release branch instead of master, you can get changesets since `my-branch`, as we explicitly only have a `--sinceMaster` flag.

## Proposed solution

- Expose the function in `@changesets/git` that takes a branch name (which the `sinceMaster` version is using under the hood)
- Add a `branch` option as a string to places which are using `sinceMaster` currently
- Add error handling around if the specified branch doesn't exist
- Add `--branch=...` to `changeset status`

## Deprecating `--sinceMaster`

I'll be honest, this flag always rubbed me the wrong way and it would be great to deprecate it. This can be two-stepped:

- Add deprecation warnings to usages of `sinceMaster` to the PR that adds `branch`
- Open a new PR with label `breaking` which removes `sinceMaster` (to be merged next time we are ready for a breaking release)

**Comment by mitchellhamilton** [comment]
Naming nit: `since-branch` instead of `branch` because `branch` sounds like it’s getting the status of the branch rather than the releases since the branch.

**Comment by Blasz** [comment]
Maybe it's a good idea to go one step further and allow it to accept any git ref (e.g. commit) and name it `--since`?
