### ISSUE TITLE
When setting `access` - respect package-specific config

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#193]
I don't explicitly know this doesn't work, but we should validate it's fine, or 'fix' it.

## Problem

Currently `access` is set on all publishes, meaning a repo probably can't have both `public` and `restricted` packages (needs actual verification that this will go wrong as well, but I think it should)

## Proposed Solution

The publish command should check if `publishConfig.access` is set in each workspace's `package.json` and then respect the package config over the changeset config.

**Comment by Andarist** [comment]
I'll try to investigate this in the following days and prepare a fix if needed.
