### ISSUE TITLE
get-github-info returning a single links.user

### ISSUE THREAD

**Issue by Andarist** [atlassian/changesets#211]
## Problem

I've noticed that this returns a single user - the one that has last touched the changeset file. Ideally, it would return either:
- original author
- all users responsible for a particular changeset

**Comment by Noviny** [comment]
Thanks! This makes sense to me as a thing to fix. I'd probably err for original author (definitely preferable to last person to modify the file)

Probably returning all responsible people in chronological order makes the most sense, and then a person writing the release line generator can set up their desired behaviour for the info.

**Comment by Andarist** [comment]
Just to give this some context - I've just changed a changeset type from minor to patch and thus the change got attributed completely to me (original author being completely lost).

**Comment by Andarist** [comment]
@mitchellhamilton I see you have merged a PR addressing this, was it a full or partial fix for this? Can this issue be closed?

**Comment by mitchellhamilton** [comment]
It fixed it to return the original author and we're probably not going to do the all users responsible for a changeset because that raises a lot more questions so yes, let's close this.

**Comment by Andarist** [comment]
That's totally fine, a single user is most often better. 

There is still a problem with the used approach though - a changeset should be attributed to change author, not the changeset author. And from what I understand you check for the latter. I understand that retrieving a change author is tricky - but maybe something could be done to at least handle this for cases when changesets are created as part of a PR (and not when added directly on the stable branch). Additionally, a frontmatter could support specifying the author somehow.
