### ISSUE TITLE
[BUG] keeps open new empty pull requests

### ISSUE THREAD

**Issue by samdenty** [atlassian/changesets#222]
## Affected Packages

https://github.com/samdenty/gqless/pull/37

## Problem

I merged the initial PR to 'Version packages' in this commit: https://github.com/samdenty/gqless/commit/e28c6aa9594ef14b09099760d247489037c3c841

Instead of publishing, it created a new empty PR:
https://github.com/samdenty/gqless/pull/34

I tried merging that again twice, then I tried creating a new changeset:
https://github.com/samdenty/gqless/pull/36

And the same happened again.

I presume this is a bug, how can I fix it?

**Comment by Noviny** [comment]
That seems like a super unfun bug.

If you want to look into why it's happening, you can find the code for the GH action [in its own repository](https://github.com/changesets/action). I'm not 100% on why you've encountered this, but you can run the action off a fork if you are looking to dig in to this.

If you are planning to investigate this, do you mind if I assign this to you for now?

**Comment by mitchellhamilton** [comment]
This is because the action doesn't support pre-releases yet, I have a branch that does but was sometimes wrong so that's why it's not on master but an update to `@changesets/read`(which was just published) should make it correct.

**Comment by mitchellhamilton** [comment]
I just merged the pre-release support, keen to hear if it fixes your problem.

**Comment by Noviny** [comment]
Closing this assuming it is fixed with Mitchell's change. Please reopen if it's not fixed.
