### ISSUE TITLE
Github "Create Changeset" action/bot

### ISSUE THREAD

**Issue by mikehazell** [atlassian/changesets#226]
It would be really handy if there were a way to create a `changeset` from within Github.

This would be especially useful in open source projects where a contributor is not familiar with the `changesets` workflow to display a `Changeset Required` check and have the contributor be able to resolve the issue without having to go back to the terminal and run an unfamiliar command.

## Affected Packages

changelog-github (? ... maybe, I'm not sure)

## Problem

Trying to keep barriers to code contribution to a minimum.

## Proposed solution

A Github bot action thing ...

**Comment by Noviny** [comment]
I... don't know how I missed this - but this is already an option with [the changeset bot](https://github.com/changesets/bot) - it leaves comments on PRs with the status of changesets, and has a link to add your own changeset to the PR.

This is designed so the maintainer can run it, not just the contributor.

**Comment by Noviny** [comment]
Is there a way that the current implementation in the bot doesn't suit your needs?

**Comment by mitchellhamilton** [comment]
I answered @mikehazell's question in TM Slack mentioning the link to add a changeset to the PR so we can close this.
