### ISSUE TITLE
Add support for `ignored` config

### ISSUE THREAD

**Issue by Andarist** [atlassian/changesets#242]
I've discussed this briefly with @mitchellhamilton yesterday and he has validated my idea and asked me to create an issue about it for further discussion.

## Problem

It seems useful to be able to opt-out of auto-publishing sometimes. Most notably when adding a new package (but working on it gradually) or working on a new version of a particular package without entering pre mode for it (might be overkill).

Currently, there is no such way, `"private": true` works the same way as other packages - it just aint being published to npm, but it's a subject to changelog/tag generation and dependencies bumps. At first it has been suggested that this use case has already been discussed [here](https://github.com/atlassian/changesets/issues/231#issuecomment-567710115), but actually it hasn't. This one is not about changing how changesets manage dependencies **permanently** (a very core logic) but rather just about "muting" certain packages *temporarily*.

## Proposed solution

Introduce `ignored` list - it would simply skip its entries in `@changesets/assemble-release-plan`.

Things to take care of so a cohesive experience can be provided
- dependencies should still be bumped (written to package.json), but it wouldn't trigger a new release
- changesets for ignored packages should be kept and shouldn't affect the release flow
- we should throw for "mixed" changesets (containing ignored and not ignored packages)

**Comment by mitchellhamilton** [comment]
> we should throw for "mixed" changesets (containing ignored and not ignored packages)

Alternatively, we could remove the not ignored packages from the changesets

---

If this is a thing that we'd like to do, I think one goal should be that it should also solve the first use case from https://github.com/atlassian/changesets/issues/231#issuecomment-567710115, I think this proposal does but I'm not totally sure.

**Comment by Andarist** [comment]
> Alternatively, we could remove the not ignored packages from the changesets

That would be quite magical and I think not something that would be expected. It's an easy-ish mistake to create mixed changesets (especially that a package can be added to the ignored list after a changeset gets created). Also one would easily miss that something didn't get published because we've removed forcefully a package from a changeset file - fixing this afterwards would also be rather cumbersome. 

After some thinking - we also shouldnt allow for publishing any dependent (direct or transitive) on the ignored package as it would be too risky. My main use case is to ignore "leaf" packages and this is safe to do.

> If this is a thing that we'd like to do, I think one goal should be that it should also solve the first use case from #231 (comment), I think this proposal does but I'm not totally sure.

The use case described there seems to me totally different - as in that use case one would like to change the timing of releasing certain packages. I just want to prevent releasing altogether.

**Comment by Noviny** [comment]
Just as an aside, I think the logic for the things you want to do boils down to:

```js
const modifiedApplyReleasePlan = async ignoredPackages => {
  let dir = await findWorkspacesRoot(process.cwd());
  let workspaces = await getWorkspaces({ cwd: dir });
  let config = await getConfig(dir, workspaces);
  let releasePlan = await getReleasePlan(dir, false, config);

  releasePlan.releases = releasePlan.releases.map(release => ({
    ...release,
    newVersion: ignoredPackages.includes(release.name)
      ? release.oldVersion
      : release.newVersion,
  }));
};
```

This is approximately the use-case I was thinking of in #231, but maybe didn't express properly. There's an implementation similar to this in a private repository (it has a step that validates the only things that we reset the version for were leaf nodes as well).

It's unclear to me whether it's better to add `ignore` as config, or add the ability for a user to write something like the above (with probably a guide to doing it and base function) that they can plug in.

**Comment by Andarist** [comment]
> It's unclear to me whether it's better to add ignore as config, or add the ability for a user to write something like the above (with probably a guide to doing it and base function) that they can plug in.

That's definitely a hard decision to make 😉 A builtin config has an important (IMHO) advantage over the ability to just manipulate a release plan - it can be implemented in a safer manner, with some opinions about how such feature should work ofc, so it still maybe wouldn't be able to cover all the use cases, but I think that an opinionated builtin solution would be good as this use case here doesn't seem to be overly rare.

**Comment by mitchellhamilton** [comment]
> A builtin config has an important (IMHO) advantage over the ability to just manipulate a release plan - it can be implemented in a safer manner, with some opinions about how such feature should work ofc, so it still maybe wouldn't be able to cover all the use cases, but I think that an opinionated builtin solution would be good as this use case here doesn't seem to be overly rare.

I agree with this.

I think that if we can get away with not allowing people to manipulate release plans, we should do it.

**Comment by Noviny** [comment]
I'm noting this as decided, that we will add an `ignored` list to the config, with suitable safety around ensuring nothing that is released depends on release nodes.

I'm not sure if I'll have immediate time to implement this, so if anyone else wants to pick it up, I'm happy to review/shepherd.

**Comment by Andarist** [comment]
This is something I need so im happy to contribute this

**Comment by Feiyang1** [comment]
@Andarist Have you started working on this? If not, do you mind me taking a shot at it?

**Comment by Andarist** [comment]
@Feiyang1 I don't mind - if you want to discuss the implementation I'm open for discussing this through Twitter's DMs or whatever, I can also help to do code review once you prepare the PR

**Comment by Andarist** [comment]
This has been implemented some time ago in https://github.com/atlassian/changesets/pull/371 by awesome @Feiyang1  🎉
