### ISSUE TITLE
Add Types

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#29]
Not having types for this makes it a lot harder to reason about and extend. We should add types.

Executive decision is that these should be be typescript types.

This is just work-to-be-done

**Comment by mitchellhamilton** [comment]
I'd be interesting in helping out on this FYI because I've been meaning to learn TS in some depth and the tooling, declaration generation and etc. around it for preconstruct.

**Comment by Noviny** [comment]
Happy for you to take this on as a task if you want. Note that there's some typing information that got removed. I'd check out bolt for the functions I pulled from there, and atlaskit for changeset files.

**Comment by Noviny** [comment]
By the v2 release, I believe this should have been achieved
