### ISSUE TITLE
Add option to increment root package.json along with packages

### ISSUE THREAD

**Issue by mattpocock** [atlassian/changesets#300]
## Problem

My team handles multiple client repositories from the same monorepo, using yarn workspaces. We all PR and commit changes to master. When we want to release code to a client, we increment the _root_ package.json version, and create a tagged release based on that version.

Changesets works beautifully for our use case, _except_ for the fact that it doesn't also increment the root package.json.

## Proposed solution

Add a flag in config.json to allow changesets to also apply semver increments to the root package.json when you run `yarn changeset version`

**Comment by Andarist** [comment]
Wouldn't it be possible to just add a simple script on your side that would run after changesets and bump this according to your needs?

From what I understand it would be slightly iffy to decide on how to bump root package.json automatically as changesets exist to aid independent versioning of monorepo packages, so what would be exact rules for bumping this?

**Comment by mattpocock** [comment]
> Wouldn't it be possible to just add a simple script on your side that would run after changesets and bump this according to your needs?

Yes, I was thinking about this. The ideal way to manage this would be able to detect from the current changeset state which semver versions to bump. I can write a script to parse the frontmatter in the .md files, which will work for our use case.

> From what I understand it would be slightly iffy to decide on how to bump root package.json automatically as changesets exist to aid independent versioning of monorepo packages, so what would be exact rules for bumping this?

You're right, this is a pretty unique use case which we should deal with in userland. Thanks for your time.

**Comment by Andarist** [comment]
It might be possible to retrieve the semver version bump from existing and exposed APIs, but I'm not an expert in that - so you would have to explore it on your own.

**Comment by NMinhNguyen** [comment]
It turns out that you can achieve this via [`@changesets/get-release-plan`](https://github.com/atlassian/changesets/tree/main/packages/get-release-plan) package. Just make sure you run it before you do `changeset version`:

```js
import getReleasePlan from '@changesets/get-release-plan';

const releasePlan = await getReleasePlan(process.cwd());
const highestVersionType = releasePlan.releases.reduce((currentType, { type }) => {
  switch (type) {
    case 'major':
      return type;
    case 'minor':
      if (currentType === 'patch') {
        return type;
      }
    default:
      return currentType;
  }
}, 'patch');

// Now you can run `changeset version`
```

But the reason I found this issue is because it appears to me that if the root `package.json` has a dependency on a monorepo package, then the root `package.json` won't have its dependencies bumped. Seems related to the original issue but perhaps warrants a separate issue to track?
