### ISSUE TITLE
Add support for the workspace protocol

### ISSUE THREAD

**Issue by zkochan** [atlassian/changesets#307]
## Problem

Both pnpm and Yarn v2 support workspace ranges.
* [About workspace ranges in pnpm](https://pnpm.js.org/en/workspaces#workspace-ranges-workspace)
* [About workspace ranges in Yarn v2](https://yarnpkg.com/features/workspaces#workspace-ranges-workspace)

When I ran `changeset status` on the [pnpm monorepo](https://github.com/pnpm/pnpm/), I got lots of the following errors:

```
Package "@pnpm/tarball-fetcher" must depend on the current version of "@pnpm/error": "1.2.0" vs "workspace:1.2.0"
```

Workspace ranges are really useful in monorepos, so I think it is crucial to support them. And it shouldn't be hard to support. You could probably just strip the `workspace:` part. Only `workspace:*` is a special case. Before publish, it is replaced with the current version present in the monorepo.

**Comment by Andarist** [comment]
Are there any differences between pnpm and berry in this regard?

**Comment by zkochan** [comment]
I don't think so. This was added by @arcanis to Yarn, I liked the idea and implemented the same in pnpm.

**Comment by Andarist** [comment]
I'll take a look into adding support for this in the following days.

**Comment by zkochan** [comment]
I need this now, so I'll submit a PR

**Comment by Andarist** [comment]
@zkochan sure, that's cool - couldn't find enough time to get to it last week and was planning to address it this weekend. Thanks for taking care of this though! I really appreciate it.
