### ISSUE TITLE
"changeset add" doesn't show changed packages because of '/' vs '\\' path issue

### ISSUE THREAD

**Issue by MichaelKapustey** [atlassian/changesets#309]
## Affected Packages
pf`pkg:git`
[https://github.com/atlassian/changesets/blob/master/packages/git/src/index.ts](https://github.com/atlassian/changesets/blob/master/packages/git/src/index.ts)

## Problem
After I change some file and run "changeset add" command I'm able to see only "unchanged packaged" in a list. While I'd like to see changed one.

It is caused by next issue:

`getChangedPackagesSinceRef  ` returns empty array when it shouldn't

You may find details below:
`getChangedFilesSince `output contains paths like"
`"C:\\src\\repository\\components\\some-component\\some-component.js"`
It is compared then to `pkg.dir + path.sep`. Where `pkg ` is element of `getPackages `output.
Here is related line:
`const fileNameToPackage = fileName => packages.packages.find(pkg => fileName.startsWith(pkg.dir + path.sep));`

`pkg.dir + path.sep` results in `"C:/src/repository/components/some-component\\"`

Obliviously that
`"C:\\src\\repository\\components\\some-component\\some-component.js".startsWith("C:/src/repository/components/some-component\\") `
returns false

## Proposed solution
Use https://www.npmjs.com/package/is-subdir

**Comment by Noviny** [comment]
Thanks for the very detailed report. Would you be able to make a PR to make this change?

**Comment by MichaelKapustey** [comment]
I think I will. We're planning to use changesets in my company's monorepo. I need to arrange "official" time dedicated to contribution.

**Comment by zkochan** [comment]
This should be closed as it was solved by https://github.com/atlassian/changesets/commit/aa840db824c321159e3b1c66ea663b4036084bd7.

When a commit fixes an issue, add `close #309` in the commit message. That way, the commit will close the issue once the PR is merged.
