### ISSUE TITLE
Lint markdown

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#31]
With remark, for preference.

Tried a quick experiment looking at how keystone-5 does it, but the config wasn't being picked up at all, so going to revisit this later.

**Comment by Andarist** [comment]
I believe this got resolved by https://github.com/atlassian/changesets/pull/486

**Comment by cap-tbouasli** [comment]
Although the PR title in #486 is lint, what was actually added was prettier, which is not a linter.
