### ISSUE TITLE
Ignore directory dependencies (the file: and link: protocols)

### ISSUE THREAD

**Issue by zkochan** [atlassian/changesets#322]
## Problem

The CLI currently fails if there are local dependencies. Local or directory dependencies are those that use the `file:<relative path>` or `link:<relative path>` spec (the link protocol is supported by Yarn and pnpm).

## Proposed solution

If a dev dependency is using a `link:` or `file:` protocol, just ignore that dependency. It will not require any update because the package's location is not changed when the versions are bumped.

**Comment by Andarist** [comment]
Q: do those protocol makes sense in all type of dependencies? Technically `"dependencies"` are probably OK, but somewhat bizarre but it doesn't make sense to use those as `"peerDependencies"`, right?

**Comment by zkochan** [comment]
I guess they are fine in prod dependencies, if the project is private. Otherwise only in dev deps.

In peer deps they cannot appear. A peer dep needs to be a range

**Comment by zkochan** [comment]
Oh, it appears that lerna uses these protocols also for prod deps. Lerna basically converts them to regular deps before publish. I think we don't need to support that as we already support workspace ranges.

**Comment by zkochan** [comment]
I am working on this
