### ISSUE TITLE
Unexpected error during version command

### ISSUE THREAD

**Issue by nightire** [atlassian/changesets#341]
## Error

```
 InternalError: preVersion is not a number
    at getPreVersion (<cwd>/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:270:11)
    at assembleReleasePlan (/home/runner/work/ui-universe/ui-universe/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:298:47)
    at version (/home/runner/work/ui-universe/ui-universe/node_modules/@changesets/cli/dist/cli.cjs.dev.js:446:21)
    at async /home/runner/work/ui-universe/ui-universe/node_modules/@changesets/cli/dist/cli.cjs.dev.js:995:11 {
  name: 'InternalError',
  _error: Error
      at new ExtendableError (/home/runner/work/ui-universe/ui-universe/node_modules/extendable-error/bld/index.js:23:24)
      at new InternalError (/home/runner/work/ui-universe/ui-universe/node_modules/@changesets/errors/dist/errors.cjs.dev.js:38:5)
      at getPreVersion (/home/runner/work/ui-universe/ui-universe/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:270:11)
      at assembleReleasePlan (/home/runner/work/ui-universe/ui-universe/node_modules/@changesets/assemble-release-plan/dist/assemble-release-plan.cjs.dev.js:298:47)
      at version (/home/runner/work/ui-universe/ui-universe/node_modules/@changesets/cli/dist/cli.cjs.dev.js:446:21)
      at async /home/runner/work/ui-universe/ui-universe/node_modules/@changesets/cli/dist/cli.cjs.dev.js:995:11
}
```

## Versions

- @changesets/cli@2.6.4
- node@v12.16.2

## Extra details

Don't know why it happens, been used changesets in this project for two months, never seeing this error before.

**Comment by zkochan** [comment]
I have also experienced this error yesterday. But I don't remember the reason. Either the same as #339 or due to having local dependencies (those that use `file:` or `link:`)

**Comment by nightire** [comment]
@zkochan Thanks for the tips. 

Issue #339 doesn't fit my situation, every package in my project has a `version` field in the `package.json`

As for local dependencies, yes I have some, but not recently additions, changesets used to works pretty well with local dependencies in my project, why it breaks now? Are there any breaking changes that I don't know about?

**Comment by nightire** [comment]
Now even if I run `yarn changesets status` locally, I see this error as well, now  I can't do anything with changesets, what's going on? How am I supposed to find the root cause of this problem?

**Comment by zkochan** [comment]
I don't see a connection at the moment but these were some recent changes related to local deps: #324

**Comment by nightire** [comment]
@zkochan Thank you very much, I'll look into it to see if I can find the reason behind.

**Comment by Andarist** [comment]
If u could share your repository this would be of great help in diagnosing the problem quicker.

**Comment by nightire** [comment]
@Andarist I understand that but unfortunately, this is a private project that I don't have the permission to share it. I'll see what I can do right now or ask for more help later.

**Comment by mitchellhamilton** [comment]
Could you share the output of this script which logs the versions of all your packages?

```js
const { getPackages } = require("@manypkg/get-packages");
(async () => {
  const { packages } = await getPackages(process.cwd());
  console.log(
    JSON.stringify(packages.map(pkg => pkg.packageJson.version), null, 2)
  );
})();
```

**Comment by nightire** [comment]
@mitchellhamilton It's OK, I had this figured out.

This is a monorepo, has two private packages in it which for sure we don't want to publish.

Currently, this project is in the pre-release phase, every package started from version '0.0.0', including those two private packages, like:

```json
{
  "initialVersion": {
	"package-a": "0.0.0",
	"package-b": "0.0.0",
	"package-c": "0.0.0",
	"private-a": "0.0.0",
	"private-b": "0.0.0"
  }
}
```

After a few times of releasing, every package becomes to version `1.0.0-rc.x`, then one of my colleagues removes "private-a" and "private-b" fields from the `.changeset/pre.json` file because he thought it is unnecessary to track private packages.

Then he did a successful release, but he didn't know after that release, the `pre.json` file becomes to something like:

```json
{
  "initialVersion": {
	"package-a": "0.0.0",
	"package-b": "0.0.0",
	"package-c": "0.0.0",
	"private-a": "0.0.0-rc.x",
	"private-b": "0.0.0-rc.x"
  }
}
```

No one noticed this little problem until I try to version up and release new versions. I spent some time to figure this out, now we back to normal.

Again, thanks for everyone's help.
