### ISSUE TITLE
README.md misleads about spec. Should just link straight to glossary/dictionary.

### ISSUE THREAD

**Issue by waded** [atlassian/changesets#347]
## Problem

README.md says "We also have a spec", "spec" a link, but the link (/docs/spec.md) says "spec is cancelle" (spelling mistake?) and links to /docs/dictionary.md. I ran into this within the first minute of reading about changesets, and I suppose people might feel this is a bit of a shell game. I certainly did.

## Proposed solution

Tighten this up. If there's no spec that's fine. Link directly to the glossary/dictionary from README.md , especially helpful because glossary terms that may be unfamiliar are used in README.md.

**Comment by mitchellhamilton** [comment]
Yep, linking to directly to the dictionary and removing the references to the spec would be great

**Comment by waded** [comment]
Thanks. I will submit PR. I'll also remove spec.md itself (there's only one other link to it, in detailed-explanation.md, so I'll change that to also link to dictionary.)
