### ISSUE TITLE
Broken link to the types package in docs/dictionary.md

### ISSUE THREAD

**Issue by waded** [atlassian/changesets#349]
## Problem

docs/dictionary.md has a broken link with text "our types package". When reading this in GitHub's markdown viewer, as in when exploring docs for changesets for the first time, clicking "our types package" led me to GitHub's 404 page.

## Proposed solution

Perhaps intended/correct target for this link is "../packages/types" instead of "./packages/types"?

**Comment by mitchellhamilton** [comment]
Yep, that's correct! Happy to accept a PR fixing this

**Comment by mitchellhamilton** [comment]
Yep, that's correct! Happy to accept a PR fixing this

**Comment by waded** [comment]
Thanks, I'll make a PR.
