### ISSUE TITLE
Questions about prerelease versions and independent mode

### ISSUE THREAD

**Issue by emmenko** [atlassian/changesets#356]
Hi,

this project looks very interesting and I'm evaluating if I can try it out to some of our monorepositories.

I have two questions first, which I couldn't find any answer in the docs.

1. **The prerelease feature changes the version by appending the `tag` name. Is there a way to specify the npm dist-tag but keep the version as-is?**
  In our case when we create a release we publish to `next` dist-tag by default. Then when we want to promote the version to `latest`, we do so by running a script manually that assigns the version to `latest`. However, the version does not change from `next` to `latest`, only the dist-tag.
  We also have canary releases, in which case the current implementation of a prerelease would work, as the version should change as well.

2. **Is "independent" mode the only available mode?**
  In Lerna there are 2 modes: locked and independent. In our case we use locked mode. I don't see a big issue if we change to independent mode as a result of moving to changesets. I just want to understand if this is the only way or if there is another "hidden" option or something.

Thanks in advance, any feedback would be appreciated.

**Comment by KingScooty** [comment]
Ha, that's so weird. I literally just came here with the exact same questions.

I want to be able to have a fixed mode in changesets so all packages bump to the same version. Similar to how React / React-DOM works. I have packages that all need to bump together regardless of whether they change. Can't seem to figure out how to do it.

**Comment by Andarist** [comment]
2. There is a linked config that should roughly do what u want here. Please recheck if it matches your expectations exactly

**Comment by zkochan** [comment]
Regarding 1, I think it would be best to leverage the package manager for publish. If you use [pnpm](https://github.com/pnpm/pnpm) you may run `pnpm publish -r --tag next` and it will publish all the packages with the next tag.

**Comment by emmenko** [comment]
> There is a linked config

Ah, where can I find that?

> I think it would be best to leverage the package manager for publish

I see, so I just use the `version` command to bump the versions (without using the prerelease feature) and then try to publish "normally" using e.g. Lerna?

Would it make sense to have it configurable in changesets, e.g. in the `publish` command or in the `pre` command? Or are there specific reasons not to do that?

Thanks for the quick feedback so far!

**Comment by Andarist** [comment]
> This one? https://github.com/atlassian/changesets/blob/master/docs/linked-packages.md

Yes, this is what I had in mind.

> Would it make sense to have it configurable in changesets, e.g. in the publish command or in the pre command? Or are there specific reasons not to do that?

Well, currently the pre mode is designed to batch - often breaking - changes. It's mostly useful for developing the next major version of your project. It doesn't have to be limited to this use case, but to extend support for other use cases you would have to post an RFC describing your desired flow so this could be discussed in more depth.

**Comment by emmenko** [comment]
> you would have to post an RFC describing your desired flow so this could be discussed in more depth

Got it. If I have some time in the next days I can try to draft something up.

---

I have another question if you don't mind, as I'm trying things out.
I noticed that private packages also get a changelog, but only if the bumped version is within the dependencies, not the dev dependencies.

I'm a bit confused about this behavior and couldn't find any useful info in the docs/code. Could you explain that, if this is the expected behavior?
You can find an example PR here: https://github.com/commercetools/merchant-center-application-kit/pull/1486

What I expected instead is that private packages do not get a changelog, only the versions bump.

Thanks a lot in advance 🙏

**Comment by Andarist** [comment]
> I noticed that private packages also get a changelog, but only if the bumped version is within the dependencies, not the dev dependencies.

I think the same happens for public packages. Updating dev dep shouldn't affect the production release, that's why dev deps do not bump versions.

> What I expected instead is that private packages do not get a changelog, only the versions bump.

Currently, it is not possible to bump the version without also changing the changelog (at least I don't think it is possible). A (somewhat) related comment/discussion about versioning private packages: https://github.com/atlassian/changesets/issues/339#issuecomment-619334412

**Comment by emmenko** [comment]
> Updating dev dep shouldn't affect the production release, that's why dev deps do not bump versions

Yes that's fine and it makes sense.
I asked because I got an error that the `CHANGELOG.md` file wasn't present, due to the fact that the version bumped of the private package was only a dev dependency.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/1110551/81548098-08706480-937d-11ea-926d-e23c8e3ef9ac.png">

You can see the [full logs here](https://github.com/commercetools/merchant-center-application-kit/runs/657665861).

I "solved" this by creating an empty `CHANGELOG.md` file in the private package. I suppose this was just an edge case and wanted to know what the behavior is with private packages.

**Comment by Andarist** [comment]
@emmenko if you could create a simplified repro case this would be very helpful to get this fixed.

**Comment by emmenko** [comment]
I guess this can be closed now. I've been using changesets across different repos for some time now and pretty much are use cases / requirements have been covered now. We're very happy with that! Thanks 🙏
