### ISSUE TITLE
Question: Changeset publish with arguments

### ISSUE THREAD

**Issue by frendable** [atlassian/changesets#360]
## Affected Packages

changeset publish

## Problem

Hi, I have a problem when want to deploy a files package component inside `dist` or `dest` folder which created after build the component.
I need to publish the only files inside `dist` or `dest` folder instead of whole files including the real source code and `dist` or `dest` folder itself

## Proposed solution

Is it possible to execute publish command with arguments like `changeset publish dist/`? or is there another way to achieve this?

Thank you.

**Comment by emmenko** [comment]
Hi, what you are asking is only related to npm (assuming you use the npm registry to publish your package).

You usually have 2 options:
- use `.npmignore` file (similarly to `.gitignore`) where you exclude the files/folders you don't want to be published (http://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html)
- use the `files` field in the `package.json`, to select only the files/folders you want to publish (https://docs.npmjs.com/files/package.json#files)

**Comment by Noviny** [comment]
Closing this as answered
