### ISSUE TITLE
Versions are downgraded in pre mode

### ISSUE THREAD

**Issue by zkochan** [atlassian/changesets#363]
## Problem

In pre mode, versions are sometimes downgraded.

Steps on a project of v1.0.0
1. enter pre mode
1. make a major release. changeset will bump the version to v2.0.0-beta.0
1. make a minor release. changeset will bump the version to v1.1.0-beta.1

## Proposed solution

The max available bump type should be used to release the next canary version, not the bump from the last, not released changeset

**Comment by Andarist** [comment]
Interesting - this sounds awfully similar to another issue that has been fixed by https://github.com/atlassian/changesets/issues/244 . We need to compare both to check what is different and why that fix has not covered all cases.

**Comment by Andarist** [comment]
@zkochan have you encountered this problem since May? Looking into the code I don't know why this would happen, so we would need to get access to a repro case so we could debug this.

**Comment by Noviny** [comment]
I'm going to close this for now, but please reopen if it's still a problem

**Comment by zkochan** [comment]
I was not using pre mode since then.
