### ISSUE TITLE
Allow to pass glob or regex to linked config

### ISSUE THREAD

**Issue by emmenko** [atlassian/changesets#364]
## Problem

When using the `linked` config option, it can get quite verbose to write and keep track of all the packages in the repo.

This becomes obvious when you want to "simulated" the "locked" mode of Lerna, where all packages follow more or less a common version (as suggested here https://github.com/atlassian/changesets/issues/356#issuecomment-625203441).

## Proposed solution

One thing that would help is to allow to pass a regex or a glob string instead of listing all packages explicitly.

For example:

```json
{
  "linked": [
    ["@changesets/*"]
  ]
}
```

Or even introduce a new option that automatically link all packages. For example:

```json
{
  "linkAllPackages": true
}
```

It would be enough to have a glob/regex, which is a bit more flexible.

What do you think?

**Comment by taras** [comment]
Backstage.io project needs this functionality as well. You can see discussion about it here https://github.com/spotify/backstage/pull/2437#discussion_r487532845

Would you be open to a PR that add this functionality?

**Comment by mitchellhamilton** [comment]
Allowing globs(using https://github.com/micromatch/micromatch) sgtm. PRs welcome.

**Comment by emmenko** [comment]
Nice, I can start working on this then. Unless @taras you would like to do that...

**Comment by emmenko** [comment]
FYI: I started working on this.

**Comment by Andarist** [comment]
I can't resist myself to say that - I **hate** globs.

https://twitter.com/sarah_federman/status/1304383012101005312

**Comment by taras** [comment]
@emmenko you might finish before I wake up :)

**Comment by emmenko** [comment]
PR is open, let me know what you think

**Comment by taras** [comment]
![](https://media.giphy.com/media/1Zt3z4uEBPZQY/giphy.gif)
