### ISSUE TITLE
Documented changes are overwritten on next update

### ISSUE THREAD

**Issue by emmenko** [atlassian/changesets#379]
I just noticed that when the "Version packages" PR gets updated, the previous entries get duplicated and/or overwritten.

For example: 

<img width="860" alt="Screenshot 2020-05-28 at 16 20 41" src="https://user-images.githubusercontent.com/1110551/83153536-5e743480-a0ff-11ea-9aeb-ce36b6cab625.png">

More specifically, it seems that the links to the commit and the author gets duplicated. Another example:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/1110551/83153775-a2ffd000-a0ff-11ea-99f2-f70e428ea311.png">

Not sure if this is a regression or it has always been an issue.

**Comment by emmenko** [comment]
Ah, could it be that I need to explicitly check out the repo with `fetch-depth: 0`, or a bigger depth?

https://github.com/atlassian/changesets/blob/64a9017aefa6b6444d83cf7802cca8e8404fb697/.github/workflows/changeset-version.yml#L16-L17

**Comment by Andarist** [comment]
Content of the PR is re-generated each time as far as I remember, so old content is not reused anyhow.

I believe this always has been like this - it just happens that a single PR had multiple changesets for a single package (which is fine) and each changeset is converted to a single displayed changelog entry, where each receives a reference to the commit, author and PR.

**Comment by emmenko** [comment]
I think the issue is related to the git history. I updated the checkout step to `fetch-depth: 50` now, let's see if it helps.

**Comment by Andarist** [comment]
If you take a look at [the linked commit](https://github.com/atlassian/changesets/commit/6d0790a7aa9f00e350e9394f419e4b3c7ee7ca6a) for the first case then you can see that everything is OK then - this is the squashed commit from the PR #359 which contains those 2 changesets.

The other case looks broken though: https://github.com/commercetools/ui-kit/pull/1343 . I'm going to classify this as a bug and we will take look into it.

**Comment by emmenko** [comment]
Thanks for taking the time to look into it.

I'll get back to you as soon as I test a bunch of new releases in the repos linked here, to see if using `fetch-depth: 50` solves the issue.

Until then, feel free to keep this on hold.
Thanks again.

**Comment by Andarist** [comment]
Damn, I've tried to reproduce it on your repository, but the correct content has been generated:
<details>
<summary>changelog</summary>

```md
# @commercetools-uikit/data-table

## 10.18.7
### Patch Changes



- [`531d3658`](https://github.com/commercetools/ui-kit/commit/531d365859eef2609ffe41b25a70edd19c23afc9) [#1345](https://github.com/commercetools/ui-kit/pull/1345) Thanks [@jonnybel](https://github.com/jonnybel)! - fix to prevent table from overflowing if it's too wide for its container, adding a horizontal scrollbar if needed



- [`13a4f703`](https://github.com/commercetools/ui-kit/commit/13a4f7037f77a041964e36460e7beb59f08a246f) [#1341](https://github.com/commercetools/ui-kit/pull/1341) Thanks [@jonnybel](https://github.com/jonnybel)! - fixed `maxWidth` prop to actually contain the table within the width value adding a horizontal scrollbar if necessary
```
</details>

I will take off the bug label as I can't repro it. If you encounter it in the future - please report the problem again so we can try to investigate again. 

> , to see if using fetch-depth: 50 solves the issue.

I really doubt this. `fetch-depth:0` should actually get more accurate information for the changelog generator.

**Comment by emmenko** [comment]
> `fetch-depth:0` should actually get more accurate information for the changelog generator.

Yeah but it wasn't set before. So the default of the `checkout` action is to fetch one single commit. Isn't that the issue here, that the information about other commits is not found?

Do you recommend to use `fetch-depth: 0`, to fetch ALL history?

**Comment by Andarist** [comment]
> Do you recommend to use fetch-depth: 0, to fetch ALL history?

Ah, yes - this is actually the current recommendation. I wasn't aware that you might have not been passing anything at all and thus fetching single commit. I would suspect now that this is the most probable cause of the reported issue.

**Comment by emmenko** [comment]
Closing this as the issue as been solved by defining `fetch-depth`
