### ISSUE TITLE
Version bumped because of peerDependencies even if the version range still satisfies

### ISSUE THREAD

**Issue by Feiyang1** [atlassian/changesets#380]
## Affected Packages

@changesets/cli version

## Problem

Currently we bump the major version of a package if it has a peerDependency on another package even if the version range still satisfies. 

Suppose `pkg-a` has a peerDependency on `pkg-b` and there is a changeset for `pkg-b` for a minor release.
```
{
    "name": "pkg-a"
    "version": "1.0.0",
    "peerDependencies": {
          "pkg-b": "1.x"
     }
}

{
    "name": "pkg-b"
    "version": "1.0.0"
}
```

After running `yarn changeset version`
```
{
    "name": "pkg-a"
    "version": "2.0.0", // triggered a major version bump
    "peerDependencies": {
          "pkg-b": "1.1.0" // 1.x satisfies 1.0.0, we shouldn't change it to `1.1.0`
     }
}

{
    "name": "pkg-b"
    "version": "1.1.0"
}
```

Since `1.x` satisfies `1.1.0`, I don't think we should bump `pkg-a` to `2.0.0`. 

## Proposed solution

We should not trigger a release for packages whose peerDependencies still satisfy the version range. 

More specifically, we should check if version range of the peerDependency still satisfies at https://github.com/atlassian/changesets/blob/master/packages/assemble-release-plan/src/determine-dependents.ts#L59-L66 and not trigger a release if it does.

**Comment by Andarist** [comment]
There is already a PR for this, but there are also valid concerns about not bumping peer dependents - some of them are outlined here: https://github.com/atlassian/changesets/pull/185#issuecomment-540313496

This is a problem though and I also would like to have a way of working around this. Right now I'm using [this patch](https://github.com/davidkpiano/xstate/blob/c29ab8a82b47c15d00b31e467b564420fb404b7f/patches/%40changesets%2Bassemble-release-plan%2B1.0.1.patch) to change the current behavior.

**Comment by Feiyang1** [comment]
Solved by https://github.com/atlassian/changesets/pull/383
