### ISSUE TITLE
No more changelogs in github since baseBranch rename

### ISSUE THREAD

**Issue by maraisr** [atlassian/changesets#398]
## Problem

I renamed my baseBranch from `master` to `main`, did this in a [single commit](https://github.com/autoguru-au/overdrive/commit/25bc36eb9918d1052dd8d9689a30d6be5ffcf935). Directly after that push, I also changed the base branch setting in GH settings also. I believe the version of the package was at [v2.0.12](https://github.com/autoguru-au/overdrive/releases/tag/%40autoguru%2Foverdrive%402.0.11) which had a nice and pretty changelog, and GH saw this as a release.

Ever since that, all my releases are merely tagged but no GH release created.

## Proposed solution

Have GH releases re-instated. 

---

Could have been introduced by #376

**Comment by maraisr** [comment]
cc @mitchellhamilton

**Comment by Andarist** [comment]
This might indeed be caused by #376 - the fix for creating proper releases after this change is on the way: https://github.com/changesets/action/pull/35

**Comment by Noviny** [comment]
@maraisr I'm closing this as probably solved - but please reopen if I am wrong
