### ISSUE TITLE
Enable configuration of the `CHANGELOG.md` file name

### ISSUE THREAD

**Issue by ifiokjr** [atlassian/changesets#401]
## Problem

Most of my projects use the `kebab-case` naming convention. To be consistent I've adopted a policy of naming all my files with lowercase names. The changelogs generated by `changesets` are the exceptions since they're all uppercase and there's no ability to change this, although I may have  missed this functionality.

## Proposed solution

Add a configuration option `changelogName` which allows for customisation of the generated changelog name.

**Comment by Andarist** [comment]
Seems like maybe this would fix your problem:  https://github.com/atlassian/changesets/pull/406 ?

**Comment by ifiokjr** [comment]
Looks great!
