### ISSUE TITLE
feat: add custom text to snapshot version

### ISSUE THREAD

**Issue by MichaelKapustey** [atlassian/changesets#414]
## Affected command

    changeset version --snapshot

## Problem

I would like to have branch name inside snapshot version: 
instead of `0.0.0-2020624135437` I'd like to have something like `0.0.0-2020624135437-my-custom-branch`

## Proposed solution

Lets agree on command and I'll create a pull request. Seems no so much sense to restrict custom text to branch names. I'd like to go with:

    changeset version --snapshot=custom-text-goes-here

While `changeset version --snapshot` would act as it was before.

**Comment by Andarist** [comment]
This sounds OK to me and I have no problem with the proposed API as well. Would love other maintainers to chime in as well though.

**Comment by mitchellhamilton** [comment]
This already works exactly like you've proposed (except the text is inserted before the date rather than after)

**Comment by zkochan** [comment]
Actually, I have a suggestion for this option. Allow specifying what chat should be used to separate the label from the timestamp.

So running `changeset version --snapshot=dev.` would create `0.0.0-dev.202007311144` instead of `0.0.0-dev-202007311144`
