### ISSUE TITLE
Lint fails when optional chaining is in use

### ISSUE THREAD

**Issue by dotansimha** [atlassian/changesets#429]
## Affected Packages

- all

## Problem

Latest `master` has updates for TS, but `prettier` fails when we optional chaining is used. Example for the error:

```
$ /Users/dotansimha/Dev/changesets/node_modules/.bin/eslint . --ext .ts,.tsx,.js

/Users/dotansimha/Dev/changesets/packages/cli/src/commands/publish/publishPackages.ts
  108:20  error  Parsing error: Expression expected  prettier/prettier
```

**Comment by Andarist** [comment]
Thanks for the report - I've prepared a fix for this: https://github.com/atlassian/changesets/pull/430
