### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by MathieuPuech** [atlassian/changesets#433]
Is there any GitLab support planned?

I don't know if there is any blockers doing this. I suppose you can do the same as done in GitHub Actions with [GitLab CI](https://docs.gitlab.com/ee/ci/) and you can do [Merge request](https://docs.gitlab.com/ee/user/project/merge_requests/index.html#merge-requests) instead of Pull Requests.

**Comment by Andarist** [comment]
I don't think there is any plan to work on this ourselves. Like you have said - this is just a matter of replicating the logic of the GitHub action and integrating that to any pipeline that you are using.

**Comment by Noviny** [comment]
The current maintainers won't be adding gitlab support, but I'd definitely welcome either docs of setting up changesets with gitlab, or if you made gitlab CI code, we'd be happy to link to that for others looking to solve the same problem.
