### ISSUE TITLE
Prereleases with breaking changes have reverted to their previous version number

### ISSUE THREAD

**Issue by ifiokjr** [atlassian/changesets#442]
## Affected Packages

**[Repository](https://github.com/remirror/remirror)**

**Packages** 

- [a11y-status](https://github.com/remirror/remirror/tree/next/packages/a11y-status)
- [jest-prosemirror](https://github.com/remirror/remirror/tree/next/packages/jest-prosemirror)
- [multishift](https://github.com/remirror/remirror/tree/next/packages/multishift)
- [prosemirror-suggest](https://github.com/remirror/remirror/tree/next/packages/prosemirror-suggest)
- [test-keyboard](https://github.com/remirror/remirror/tree/next/packages/test-keyboard)

**Changelogs**

- [a11y-status](https://github.com/remirror/remirror/blob/next/packages/a11y-status/CHANGELOG.md)
- [jest-prosemirror](https://github.com/remirror/remirror/blob/next/packages/jest-prosemirror/CHANGELOG.md)
- [multishift](https://github.com/remirror/remirror/blob/next/packages/multishift/CHANGELOG.md)
- [prosemirror-suggest](https://github.com/remirror/remirror/blob/next/packages/prosemirror-suggest/CHANGELOG.md)
- [test-keyboard](https://github.com/remirror/remirror/blob/next/packages/test-keyboard/CHANGELOG.md)

## Problem

After upgrading to the latest version of `@changesets/cli@2.10.0` while in `pre` mode all the non-scoped packages which are also unlinked have reverted to their old versions with the same prerelease tag (`next`) applied. I didn't check before merging the pull request and I missed this happening a couple of times.

## Proposed solution

I'm not sure what caused the change. I've released several times in the past without issue.

**Comment by Andarist** [comment]
Thanks for reporting the issue - I will make sure to investigate this soon.

**Comment by Andarist** [comment]
A fix for this is here: https://github.com/atlassian/changesets/pull/446 .
