### ISSUE TITLE
`changeset` command crashes when default editor is vscode with empty message

### ISSUE THREAD

**Issue by ifiokjr** [atlassian/changesets#445]
## Affected Packages

Issue with `@changesets/cli`

## Problem

The default editor on my system is `vscode`. When running `yarn changeset` command I accidentally pressed <kbd>Enter</kbd> without typing any text and it caused my machine to crash. 

It kept creating new tabs in the `vscode` editor, and even when I quit (multiple times) it created up to 50 new `vscode` editor instances. I managed to capture a tiny bit of it before my machine froze. 

![2020-08-17 14 20 17](https://user-images.githubusercontent.com/1160934/90401794-5f7d8800-e096-11ea-8afa-28361357106f.gif)

**Comment by Andarist** [comment]
Sorry about that!

@zkochan could you take a look at this one?

**Comment by zkochan** [comment]
@MichaelKapustey have you experience ed this issue?

**Comment by MichaelKapustey** [comment]
No I never tried vscode. Seems to be editor specific, since default ones are working correctly.

**Comment by MichaelKapustey** [comment]
Maybe it has to deal something with vscode autosave issue. There is a "while" loop in a code. We may allow external editor for 3 times and then fall back to default logic.

**Comment by pkieltyka** [comment]
any updates on this? vscode is pretty popular and this infinite loop renders changesets difficult to use with it. I'm a first time user of changesets (and maybe my last), and this issue describes how my first experience looks

**Comment by zkochan** [comment]
We could probably just remove the loop. Not sure why it is needed.

**Comment by pkieltyka** [comment]
or at least remove the option of using $EDITOR altogether when submitting an empty line, and just print to the user to edit .changeset/blah-blah.md before they commit, etc. I'm unable to adopt changesets in my project due to this bug as I know it'll crash many of my teammate's systems as it has for me -- and after that I know they'll be upset with me for introducing changesets into our project

**Comment by Andarist** [comment]
@pkieltyka the fix has been published, I hope you'll give Changesets another chance 😉

**Comment by pkieltyka** [comment]
thank you @zkochan and @Andarist -- I really appreciate it. We've adopted changesets and it's working wonderfully for us. I believe changesets has such high potential to lead a path of developer tools for release management, especially for JS/TS projects, but even beyond someday (as a different toolchain of course, but same concepts). Other then a few of the bugs/quirks (which are solvable), it's an amazing product already.
