### ISSUE TITLE
Error: could not parse changeset - invalid frontmatter: ---

### ISSUE THREAD

**Issue by nategreen** [atlassian/changesets#461]
## Affected Packages

Looks like it's @changesets/parse?

## Problem

When running `changeset version` locally, I get an error like:

```
�  error Error: could not parse changeset - invalid frontmatter: ---
�  error "@mri/components": patch
�  error "@mri/elements-common": patch
�  error "@mri/svg-icons": patch
�  error "@mri/bootstrap-theme": patch
�  error "@mri/scss-all": patch
�  error ---
�  error
�  error Several small changes for tooling or CI, related to transition from rush.js back to PNPM and changesets.
�  error
�  error     at parseChangesetFile (C:\dev\mri-design-system-3\node_modules\.pnpm\@changesets\parse@0.3.6\node_modules\@changesets\parse\dist\parse.cjs.dev.js:14:11)
�  error     at C:\dev\mri-design-system-3\node_modules\.pnpm\@changesets\read@0.4.6\node_modules\@changesets\read\dist\read.cjs.dev.js:89:30
�  error     at async Promise.all (index 0)
�  error     at async getChangesets (C:\dev\mri-design-system-3\node_modules\.pnpm\@changesets\read@0.4.6\node_modules\@changesets\read\dist\read.cjs.dev.js:93:48)
�  error     at async Promise.all (index 0)
�  error     at async version (C:\dev\mri-design-system-3\node_modules\.pnpm\@changesets\cli@2.10.3\node_modules\@changesets\cli\dist\cli.cjs.dev.js:454:34)
�  error     at async run$1 (C:\dev\mri-design-system-3\node_modules\.pnpm\@changesets\cli@2.10.3\node_modules\@changesets\cli\dist\cli.cjs.dev.js:1104:11)
```

I got this error when I had not edited the file whatsoever, and it had already been pushed up, handled successfully by `changeset version` in CI, etc. So it must be something on my local machine.

Looking at the regex parsing the front matter, it looks like it is matching only when there is whitespace before the first `---`:

```js
const mdRegex = /\s*---([^]*?)\n\s*---\n([^]*)/;
```

So I tried adding some whitespace...spaces, newlines, whatever...but nothing worked.

**Comment by Andarist** [comment]
> Looking at the regex parsing the front matter, it looks like it is matching only when there is whitespace before the first ---:

Not quite, it allows any whitespace before `---` but it doesn't require it. `*` is a quantifier that matches between 0 and unlimited times.

It's hard for me to tell why this would fail for you. Could you share a runnable repro case or try to debug this? If you could dump the exact char codes passed to `parseChangeset` (or whatever the final function is called) that could be very helpful.

**Comment by nategreen** [comment]
> `*` is a quantifier that matches between 0 and unlimited times.

Oh goodness, my bad, thought it was one or more times 😊.

Yes, I'll see what I can do. 👍

**Comment by Andarist** [comment]
Could you check if maybe you have some additional whitespace after the second `---` but before the line break?

**Comment by Andarist** [comment]
It might also be just not handling newlines on Windows correctly because this fails:
```js
`---
"@mri/components": patch
---

Several small changes for tooling or CI, related to transition from rush.js back to PNPM and changesets.`
.split('\n')
.join('\r\n')
.match(/\s*---([^]*?)\n\s*---\n([^]*)/)
```

**Comment by nategreen** [comment]
No extra whitespace after the `---`.

> It might also be just not handling newlines on Windows

I am indeed on Windows. 👍

**Comment by Andarist** [comment]
I believe that I've prepared a fix for your problem: https://github.com/atlassian/changesets/pull/462

**Comment by nategreen** [comment]
@Andarist @mitchellhamilton I was unable to test this out—looks like `@changesets/read` still depends on `@changesets/parse@0.3.6`. (I tried updating to the latest version of `@changesets/cli`, then I tried installing `@changesets/parse@0.3.7` directly, but neither worked.)

**Comment by nategreen** [comment]
Ah, never mind, `pnpm update @changesets/parse --depth 3` worked. The issue is indeed solved. Thanks for your help @Andarist!
