### ISSUE TITLE
Invalid command prerelease

### ISSUE THREAD

**Issue by tpluscode** [atlassian/changesets#464]
## Problem

It's impossible for me to create a prerelease. The CLI help advertises a `prerelease` command but when I call `changeset prerelease` it it return an error saying 

> `🦋  error Invalid command prerelease was provided`

If I add the `<tag>` parameter like `changeset prerelease beta` the error is 

> `🦋  error Too many arguments passed to changesets - we only accept the command name as an argument`

Using version 2.10.3

**Comment by Andarist** [comment]
This example usage was incorrect - probably something that got in unnoticed when iterating over pre mode feature. I've prepared a PR with the fix here: https://github.com/atlassian/changesets/pull/465
