### ISSUE TITLE
error Error: Failed to find where HEAD diverged from master. Does master exist?

### ISSUE THREAD

**Issue by Bowriverstudio** [atlassian/changesets#468]
## Affected Packages

warn It looks like you already have changesets initialized. You should be able to run changeset commands no problems.
✨  Done in 0.81s.
~ $: 
~ $: npx changeset

🦋  error Error: Failed to find where HEAD diverged from master. Does master exist?

Github now by default uses "main" instead of "master".  Is there a workaround for this?

**Comment by Andarist** [comment]
Most likely you can set `"baseBranch": "main"` in your config to fix this.

**Comment by Bowriverstudio** [comment]
You are correct thank you

**Comment by ishan123456789** [comment]
Should this be added to the Readme since all the new Projects main is the branch and googling I wasn't directed to the right place? I'll raise a PR
