### ISSUE TITLE
Cannot publish to npm registry for the first time

### ISSUE THREAD

**Issue by acao** [atlassian/changesets#470]
## Affected Packages

not sure?

## Problem

`changeset publish` gives me an error like this

![image](https://user-images.githubusercontent.com/1368727/95665958-0fb1bf00-0b23-11eb-9748-898c379e1a26.png)

it does *not* 404 on one package that already has an npm registry entry

**Comment by Noviny** [comment]
Are they all in the `@relay-graphql-js` scope?

Also, would you mind posting your changesets config here for me?

**Comment by acao** [comment]
3 out of 4 are. i managed to publish them all locally first, and then changesets worked swimmingly!

i had the same exact 404 error when running npm publish manually in a single workspace, and I learned I needed to use `npm publish —access public` flag for the first package published to the brand new scope.

once i published a single package to the scope, `changeset publish` worked great!

**Comment by acao** [comment]
https://github.com/relay-tools/relay-graphql-js/blob/main/.changeset/config.json here’s the config fwiw!

**Comment by Noviny** [comment]
Oh weird - the config there specifies access as public, but isn't being respected. That's definitely still a bug. Thanks for the link.

**Comment by Andarist** [comment]
I've checked out [the commit that has failed](https://github.com/relay-tools/relay-graphql-js/commit/61e45b4a8865f65c84fa1918f407e4ce4aeb8705) and everything looks OK for me there, the publish command is being executed with such args for all packages:
```sh
npm publish --json --access public --tag latest
```

So it's very hard tell what has gone wrong here 🤔

**Comment by Andarist** [comment]
Hm, I guess the requires step is to create an organization on npm beforehand, maybe you have done that afterwards?

**Comment by Andarist** [comment]
I will assume that the issue could been related to the fact that the organization on npm could have been created **after** trying to publish packages. If the issue was not that and if the issue persists - please let us know, I can reopen this ticket if we get more info on the subject.
