### ISSUE TITLE
How do I fix a prerelease without changelog entry?

### ISSUE THREAD

**Issue by nategreen** [atlassian/changesets#479]
**This is more of a question. If there's a more appropriate forum for this, let me know.**

## Problem

When I am in pre-release mode, I make a minor change (let's say 1.0.0 -> 1.1.0-next.0). Afterward, I discover that I messed it up, and I need to fix the minor change that I made. It's not a patch to 1.0.0, so it seems like it'd be confusing to see:

> ## 1.1.0
> 
> - Add new `foo` feature
> - Fix `foo`

An empty changeset didn't publish anything at all (which makes sense). An empty changeset (content-wise) with "my-package": "minor" in the front-matter added a blank changelog entry, which is also not ideal.

Is there a way to do this, that I'm not thinking of?

**Comment by Andarist** [comment]
So - this part of the flow is somewhat iffy and, unfortunately, manual. 

I'm not sure what's the best approach here - I can only tell what I have been doing with Emotion. If you want to fixup prerelease then you have 2 possible scenarios:
1. u want to release the final version immediately - it might be worth just *not* not writing about this fix as it hasn't affected the stable release line, or you can add a changeset about it with a note that this was only a fix for the prerelease that you have published
2. u want to publish a new prerelease version with a fix (this will result in `1.1.0-next.1`) and for this version, it makes sense to include a message about it. Like you have mentioned - it doesn't make much sense to include it in the final `1.1.0` changelog and thus I have been removing such changeset files manually after releasing a fixup prerelease version. A changeset is just a markdown file so if you remove it with a regular commit no harm will be done to anyone. Even if this is at the moment somewhat manual and requires your judgment on how you want to approach this it shows how more flexible this approach is over 100% automated ones.

**Comment by nategreen** [comment]
Thanks for the explanation. I am definitely thankful for the more flexible, unopinionated approach.

> add a changeset about it with a note that this was only a fix for the prerelease that you have published

That's what I've done, even though it's a little awkward. Good point about manually removing the changeset files after prerelease published...hadn't considered that. Thanks!
