### ISSUE TITLE
Meta changes

### ISSUE THREAD

**Issue by krzkaczor** [atlassian/changesets#489]
## Problem

Sometimes changes won't end up in the final artifact but rather will impact the product in some other way.

For example:
- improving CI setup,
- improving docs,

Let's call these meta changes.

I am pretty new to changesets but I think there is no way to express such changes in the changelog, yet I think it's often valuable to note them. 

## Proposed solution

Introduce new change type - `meta`, next to `patch`/`minor`/`major`. This wouldn't bump package version in any way but would endup in the changelog.

**Comment by Andarist** [comment]
You can use `none` type but I'm not sure if those get printed in changelog files. I would have to re-check it later.

**Comment by krzkaczor** [comment]
I just tried running `changesets version` with a single changeset with type `none` (and another one with `patch`) and it resulted in all changes being applied to a random package in my monorepo 😱

**Comment by Andarist** [comment]
😱 is this a public repository that I could take a look at? I'm not using `none` changesets myself but I know that there are people using them and we haven't received reports like this yet.

As to the original discussion - why would you like to communicate to users, for example, improved CI setup? What impact does it have on them? It seems like an information noise to me. Additionally, currently, changesets only support per-package changelogs and things like this are rather "global" for the whole monorepo. There have been requests for things like a top-level changelog etc and we are open to those ideas but some design (& implementation) has to go into them first.

**Comment by krzkaczor** [comment]
It's still reproducible in https://github.com/earl-js/earl Clone it, change any changeset file to `none` from `patch`. Run `yarn changeset version` and realize that `example-plugin` version was bumped (but `earljs` should have). 

> As to the original discussion - why would you like to communicate to users, for example, improved CI setup? What impact does it have on them? It seems like an information noise to me. Additionally, currently, changesets only support per-package changelogs and things like this are rather "global" for the whole monorepo. There have been requests for things like a top-level changelog etc and we are open to those ideas but some design (& implementation) has to go into them first.

It greatly depends on who is the target of your changelog. Sometimes it's fine to show progress on not user-facing things for example to get other contributors up to speed with changes.

I think that ability to group some changes as `internal` (or something similar) would not only not increase noise in the changelog for regular users but also give maintainers a way to sum up changes for other developers/contributors.

**Comment by Andarist** [comment]
> It's still reproducible in https://github.com/earl-js/earl Clone it, change any changeset file to none from patch. Run yarn changeset version and realize that example-plugin version was bumped (but earljs should have).

Could you point me to the exact commit and post a diff that leads to unexpected behavior? I've gone back to [1e3951d](https://github.com/earl-js/earl/commit/1e3951de69ae8ec40817707e07cd4a0cd2c0cf72) and tried changing [giant-cars-cry.md](https://github.com/earl-js/earl/blob/1e3951de69ae8ec40817707e07cd4a0cd2c0cf72/.changeset/giant-cars-cry.md) but had no luck with reproducing it.

> I think that ability to group some changes as internal (or something similar) would not only not increase noise in the changelog for regular users but also give maintainers a way to sum up changes for other developers/contributors.

One thing that I find problematic with this is that Changesets revolve around releases but you are wanting to "document" internal changes that have **immediate** effect on the repository - the timing for both is just not the same. So in a sense, it doesn't make sense to use Changesets for this particular use case. It seems that maintaining a single `development_noted.md` should be enough for describing such internal changes 🤔

**Comment by krzkaczor** [comment]
It was happening: https://github.com/earl-js/earl/commit/1e3951de69ae8ec40817707e07cd4a0cd2c0cf72

That's strange, I can't reproduce it either now. 🤷 

I am fine with closing this.

**Comment by Andarist** [comment]
What about your original feature request? Is some form of this still something you'd like to see? Or maybe you have re-consider the need for this after the discussion here?

**Comment by krzkaczor** [comment]
Your arguments make sense. However, I still feel limited by the changesets but it's just me maybe. I guess I need to use it more before I make up my mind. I was also the first one to bring up this issue so I guess folks are fine with the current state of things. 

I will probably experiment on my own with how to structurize changelogs so users get the most value of them.

**Comment by Andarist** [comment]
There were some similar requests (but not the same in the past) - we'd like to cover more workflows but we need to first observe such feature requests to be able to design a proper solution.

I hope you will enjoy Changesets after working with them a little bit more (I highly recommend setting up both our bot and our GitHub action). I'm certainly very happy with this project - note that I'm just a user who tries to help out here, not the original author of Changesets, so it's not like I'm trying to advertise my own project, I'm just spreading the love for what I have found to be very useful.

It's also interesting that both Yarn 2 and Rush.js have developed, independently, somewhat similar solutions for this exact problem - so I would say that we are onto something here 😉
