### ISSUE TITLE
Support for the custom pack script

### ISSUE THREAD

**Issue by Andarist** [atlassian/changesets#492]
## Problem

There are times when one would like to alter existing files when packing a library without actually committing the changes to the repo. Examples:
- rewrite relative links in the `.md` files so they can work on the npm page (mentioned here: https://github.com/emotion-js/emotion/pull/2120 )
- pack an alternative directory (example of such a thing in the wild - https://github.com/jquense/semantic-release-alt-publish-dir )

## Proposed solution

It would be cool if Changesets would accommodate this by accepting a custom `pack` script (per package?) which would default to `npm pack`. With that in place, we would alter the call to `npm publish` to use the resulting archive.

**Comment by mitchellhamilton** [comment]
You could write a script that rewrites the READMEs in Emotion's release script and it would solve the problem without adding anything to Changesets, no?

The second use case seems like it's solved with #428, no?

**Comment by Andarist** [comment]
> The second use case seems like it's solved with #428, no?

Oh, totally forgot that this is already a thing.

> You could write a script that rewrites the READMEs in Emotion's release script and it would solve the problem without adding anything to Changesets, no?

Seems like a brain fart on my side 🤔 Should indeed work just OK with `"release": "node ./rewrite-links.js && changeset publish"`, when publishing the git's cwd doesn't have to be "clean" after all.
