### ISSUE TITLE
Detect insufficient commit history for changelog in shallow repo, and deepen clone

### ISSUE THREAD

**Issue by RoystonS** [atlassian/changesets#494]
## Affected Packages

`@changesets/changelog-git`@0.1.6
`@changesets/cli`@2.11.2

## Problem

I've been trying to diagnose why, when I run `changeset version` locally I get changelog files with correct commit history, but when my Github action or other build tools run it, all the commits show the same (latest) commit id.

This is, obviously, because on my build tools I'm running with a 1-commit shallow clone. (See also https://github.com/atlassian/changesets/issues/379.)

The recommendation at the moment seems to be "run with --depth 0", i.e. "don't use shallow clones".  That doesn't really scale, unfortunately. We have some really large (20k, 30k+ commit) repos where it's really important that we use shallow clones for builds.

Running with a deeper - but fixed - shallow clone (e.g. `--depth 50`) is also not a great option: it's entirely likely that the commits mentioned in our changelog will be older than 50 commits ago.

Would it be difficult to automatically deepen the clone if it's found that the current depth is insufficient?  We have some code that automatically does this for some of our visual-regression baseline comparisons (e.g. if our baseline details are outside of the current clone depth).

## Proposed solution

I don't yet know much about the architecture of `changesets`.  I'd be happy helping out writing some code that does the automatic deepening, as we have some experience with that, but does that require support from the changelog APIs to indicate that the correct commit was not found?

**Comment by Andarist** [comment]
Automatic deepening sounds awesome! Would bring the best correctness and perf to the users.

The `commit` is obtained here:
https://github.com/atlassian/changesets/blob/fd53ca2acb0a955bc87af090daba5aa41c2bab69/packages/apply-release-plan/src/index.ts#L206
So I assume that tweaking this function should be enough and changelog generators wouldn't have to be touched at all.

**Comment by RoystonS** [comment]
Great. The alternative approach would be to have the changelog generator realise that the returned commit is the deepest (grafted) commit of the clone and there they should auto-deepen.  But that's not as elegant.

I'll see what I can get together.

**Comment by RoystonS** [comment]
Deepening the clone by N commits is easy, with `git fetch --deepen=N`.  That flag was introduced in Git 2.11 (September 2017), which seems a reasonable ask.

Detecting whether our shallow clone covers the actual point at which the changeset files were added is slightly tricky: Git doesn't expose it in obvious ways, but I've figured out a way to do it reliably.

I'll jot down my thoughts so far and explain the reasoning:

**Option 1 - check if we have the parent commit**

`getCommitThatAddsFile` currently calls
`git log --diff-filter=A --max-count=1 --pretty=format:%h <filename>`

This translates as "give me the hash of the commit where this file was added, or the oldest commit in the clone, whichever is newer".
The problem is detecting whether it's giving us the real commit or the oldest commit.

Adding a format specifier of `%p` asks for the parent of the commit. If the parent commit isn't present in the repo (i.e. if we're being given a commit that is merely the oldest we have), it emits an empty string.

So, we can repeatedly deepen the clone until a parent commit appears. We then know that the reported commit is legitimate.

This works nicely _unless the commit that introduced the file has no parent commit_.
That happens if the changeset file was introduced as the first commit in the repo.
In that case, we'll keep deepening the clone, looking for the parent commit, but will never find it.
We can detect that we've unshallowed the entire clone by using `git rev-parse --is-shallow-repository`. If we hit that point,
we know that the commit hash is legitimate.

**Option 2 - use `git blame` boundary detection**

This is how I've detected the boundary before: you can run `git blame --line-porcelain`.
This gives a machine-readable blow-by-blow account of every line, and has specific support for indicating a boundary commit.
The downside is that it doesn't tell you when a file was added, just when each line in the file was last touched.
So, again, if you have edited a changeset file since you originally added it, and changed every line, we wouldn't be able
to detect the actual adding commit.

I don't think it's an appropriate solution here as we want to know when the changeset file was actually added, which blame can't guarantee to provide.

**Option 3 - use git log decorators**

The `%d` and `%D` format specifiers emit text containing the word 'grafted' if we're looking at a boundary commit.
e.g.

`git log --diff-filter=A --max-count=1 --pretty=format:%h:%D .changeset/wild-trainers-trade.md`
produces
`3bdd6df:grafted, HEAD -> main, origin/main, origin/HEAD`

The main problem here is that this feels like human-readable (not machine-readable) text that could change at any time.
Depending on the word 'grafted' being present at the start might be a bit fragile.  Depending on it being present _somewhere_ wouldn't work if somebody had a branch called 'grafted'.

---

So Option 1 seems like a no-brainer.

Here are those git commands in practice:

1. We have a depth-1 clone. Log out latest commit:
```
$ git log --oneline .changeset\fair-waves-change.md
3bdd6df (grafted, HEAD -> main, origin/main, origin/HEAD) another change 34
```
2. Get changeset-add commit and its parent:
```
$ git log --diff-filter=A --max-count=1 --pretty=format:%h:%p .changeset\fair-waves-change.md
3bdd6df:
```
3. That has no parent, so we're either at the edge of the shallow clone or it's a commit that genuinely has no parent. Test for unshallow clone, otherwise deepen:
```
$ git rev-parse --is-shallow-repository
true
$ git fetch --deepen=50
remote: Enumerating objects: 211, done.
remote: Counting objects: 100% (201/201), done.
remote: Compressing objects: 100% (95/95), done.
Receiving objects: 100% (156/156), 13.76 KiB | 2.75 MiB/s, done.
Resolving deltas: 100% (98/98), completed with 12 local objects.
```
4. [repeat from step 2] Get changeset-add commit and its parent:
```
$ git log --diff-filter=A --max-count=1 --pretty=format:%h:%p .changeset\fair-waves-change.md
1f98b6c:ac83817
```
Hooray, we have a real commit id (`1f98b6c`), and we know it's real because we have its parent.

**Comment by Andarist** [comment]
Option 1 sounds good 👍

**Comment by RoystonS** [comment]
Yup. I'm TDDing it right now.
