### ISSUE TITLE
Opening external editor does nothing when editor is a terminal process

### ISSUE THREAD

**Issue by with-heart** [atlassian/changesets#498]
## Affected Packages

`@changesets/cli`

## Problem

`$EDITOR` on my system is set to `NVIM_TUI_ENABLE_COLOR=1 nvim`. When I attempt to open a changeset summary in an external editor, nothing happens.

**Comment by Andarist** [comment]
I've reported the issue here: https://github.com/mrkmg/node-external-editor/issues/24

**Comment by with-heart** [comment]
Turns out the `NVIM_TUI_ENABLE_COLOR` flag was removed from `nvim` awhile ago, so I've resolved this personally by getting rid of that. Not sure if it's worth leaving this open or not since it's not directly a `changesets` issue.

**Comment by Andarist** [comment]
Ye, let's close for now and see if we get an answer to the issue in the `node-external-editor`
