### ISSUE TITLE
Build github addon

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#5]
Build a github addon to alert when there is no changeset present in a PR (without this changesets are v hard to recommend to open source projects)

Current design idea:

## On PR Creation

Leave a comment with the changeset status (bonus: list packages changed, and the version bump they are receiving)

Changeset status should look something like:

❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌
NO CHANGESET PRESENT
❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌

or:

✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
This PR has a changeset
✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
(optional changeset version info)

## On PR Update

Do NOT add a new comment - edit and update the existing changeset comment.

**Comment by mitchellhamilton** [comment]
It would be cool if this thing could look at what packages have changed and say something like "Hey, looks like LIST OF PACKAGES have changed, you might need a changeset for them".

**Comment by Noviny** [comment]
Hm. In this regard would you expect the above to look more like:

✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅
All changed packages have a changeset
✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅✅

✅ packageA is being updated as a minor
✅ packageB is being updated as a patch
✅ packageC is being updated as a patch
---

⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️
 Not all changed packages have a changeset
⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️⚠️

✅ packageA is being updated as a minor
⚠️ packageB has been changed, but does not have a corresponding changeset
⚠️  packageC is being updated as a patch, but does not contain any changes

---
❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌
This PR has no changeset
❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌❌

❌ packageA has been changed, but does not have a corresponding changeset
❌ packageB has been changed, but does not have a corresponding changeset
❌ packageC has been changed, but does not have a corresponding changeset
---

I think under this system, the ✅ and ⚠️ can probably have the sheer number of initial symbols for impression toned down. (maybe exes as well)

Providing the kind of version update in 'exists in changeset' adds quite a lot of complexity so I'd probably leave it out of the initial build - possibly changesets should have an `analyze` command that just returns the packages and version type changes, without performing operations?

See also the packageC case in the warn example where it's detecting false positives, which I don't know if it's useful.

**Comment by mitchellhamilton** [comment]
Kind of like that, yes.

I think using ⚠️ over ❌  for the "package x has been changed, but does not have a corresponding changeset" thing would probably be good because of the cases where packages shouldn't(or rather don't need to) have a changeset. (e.g. tests, some docs, etc.) 

> Providing the kind of version update in 'exists in changeset' adds quite a lot of complexity so I'd probably leave it out of the initial build 

Totally agree that it doesn't need to be exist right away.

> possibly changesets should have an analyze command that just returns the packages and version type changes, without performing operations?

An analyze command would be cool.

> See also the packageC case in the warn example where it's detecting false positives, which I don't know if it's useful.

Yeah, I'm not sure if it's super useful because there are lots of cases where a package needs to be released even if the source of it hasn't changed(e.g. a change to the build system) but I don't think it really hurts to have it.

Also, I think that the comment should explain what changesets are(or maybe link to something that explains changesets) because on open source projects where there might be lots of contributors who might not completely read the contributing docs, it'd be annoying to have people constantly going "what does that comment mean? what's a changeset? why do i need one?", especially because changesets aren't really a common thing in the ecosystem right now.

**Comment by Noviny** [comment]
Yeah, I definitely want to link out to something that explains changesets.

I was using ❌ for all entries when there was no changeset present, and ⚠️ when there was a changeset present, but it was not included. Also, I have no idea why the text is so large.

**Comment by mitchellhamilton** [comment]
> ⚠️ when there was a changeset present, but it was not included

I'm confused, where is the changeset "present" and where is it not "included"?


> Also, I have no idea why the text is so large.

Did you do (note the lack of an empty line) this? because doing that makes the text a heading

```md
some text
---
```

**Comment by Noviny** [comment]
It's the difference between "Not all changed packages have a changeset", for which I would use ⚠️ for packages that aren't mentioned and "This PR has no changeset" where I want to use ❌ for everything for loud signaling.

**Comment by mitchellhamilton** [comment]
Ah, that makes sense. I'm not totally sure if using loud signalling for "This PR has no changeset" is the right thing to do because I feel like it implies that all PRs should have changesets which isn't true, I don't feel super strongly about it though but I feel like it's worth questioning.

**Comment by Noviny** [comment]
If we have the more granular info I think it's less important to loudly call out.

**Comment by mitchellhamilton** [comment]
Thought of another thing this could do: add GitHub labels to PRs with the highest bump type in that PR so while scanning a PR list, people can visually see what PRs would be easier or harder to review and prioritize accordingly. (this is assuming that changes which only require a patch bump would be easier to review changes that require a major bump but i feel like that's a pretty safe assumption)

**Comment by Noviny** [comment]
Extra point: Mention the commit message you checked, so if the bot fails and stops updating, you can see that. Probably abbreviate this if it's more than X characters.

**Comment by mitchellhamilton** [comment]
For the putting the commit message in the comment thing, if you put a commit sha in a comment, GitHub automatically makes it a link and if you hover over it, it shows the commit message and things. That might be better than having the message, especially since you might have multiple commits with the same name or etc.

👇 is a sha from this repo as an example

9723fe3b60cbfdff1c9adc3f7319c40edcd5c8b5

**Comment by Noviny** [comment]
👍 Good call - will feed this back up.

**Comment by Noviny** [comment]
Testing a thing 9723fe3b60cbfdff1c9adc3f7319c40edcd5c8b5

**Comment by Noviny** [comment]
This exists in its basic form now: https://github.com/apps/changeset-bot

Huge thanks to @pyupew for implementing this.

Code for the bot got bundled into [this repository](https://github.com/glad-docs/brisk-docs) (for now). PRs to that are welcome. I'm thinking of closing this issue, and raising issues against brisk-docs for now, however not all of the discussion points from here have been implemented so /shrug.

**Comment by JedWatson** [comment]
As discussed IRL with @Noviny, let's change the "no changeset" and "sweet changeset y'all" messages to the following:

---

###  💥 No Changeset

Latest commit: 6ee87bfeea7cf41c8b919d6cc52118853e3e3435

Merging this PR will not cause any packages to be released. If these changes should not cause updates to packages in this repo, this is fine 🙂

**If these changes should be published to npm, you need to add a changeset.**

[Click here](https://github.com/Noviny/changesets/blob/master/docs/adding-a-changeset.md) to learn what changesets are, and how to add one.

---

###  🦋  Changeset is good to go

Latest commit: 6ee87bfeea7cf41c8b919d6cc52118853e3e3435

**We got this.**

Not sure this means? [Click here](https://github.com/Noviny/changesets/blob/master/docs/adding-a-changeset.md) to learn what changesets are.
