### ISSUE TITLE
ValidationError for `changeset status` with glob in linked package config

### ISSUE THREAD

**Issue by timbonicus** [atlassian/changesets#505]
## Affected Packages

config

## Problem

Since #458 glob expressions are allowed in linked and ignored packages. Trying to use `changeset status` with a glob expression in `linked` produces a ValidationError:

```shell
$ yarn changeset status
🦋  error ValidationError: Some errors occurred when validating the changesets config:
🦋  error The package "*" is specified in the `linked` option but it is not found in the project. You may have misspelled the package name.
🦋  error     at parse (/Source/backstage/node_modules/@changesets/config/dist/config.cjs.dev.js:173:11)
🦋  error     at Object.read (/Source/backstage/node_modules/@changesets/config/dist/config.cjs.dev.js:64:10)
🦋  error     at async getReleasePlan (/Source/backstage/node_modules/@changesets/get-release-plan/dist/get-release-plan.cjs.dev.js:21:22)
🦋  error     at async getStatus (/Source/backstage/node_modules/@changesets/cli/dist/cli.cjs.dev.js:877:23)
🦋  error     at async run$1 (/Source/backstage/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1121:11) {
🦋  error   _error: Error
🦋  error       at new ExtendableError (/Source/backstage/node_modules/extendable-error/bld/index.js:23:24)
🦋  error       at new ValidationError (/Source/backstage/node_modules/@changesets/errors/dist/errors.cjs.dev.js:16:1)
🦋  error       at parse (/Source/backstage/node_modules/@changesets/config/dist/config.cjs.dev.js:173:11)
🦋  error       at Object.read (/Source/backstage/node_modules/@changesets/config/dist/config.cjs.dev.js:64:10)
🦋  error       at async getReleasePlan (/Source/backstage/node_modules/@changesets/get-release-plan/dist/get-release-plan.cjs.dev.js:21:22)
🦋  error       at async getStatus (/Source/backstage/node_modules/@changesets/cli/dist/cli.cjs.dev.js:877:23)
🦋  error       at async run$1 (/Source/backstage/node_modules/@changesets/cli/dist/cli.cjs.dev.js:1121:11)
🦋  error }
error Command failed with exit code 1.
```

I am encountering this with [backstage/backstage](https://github.com/backstage/backstage/blob/master/.changeset/config.json) which has the linked configuration:

```
"linked": [["*"]],
```

**Comment by Andarist** [comment]
Could you take a look at this PR https://github.com/atlassian/changesets/pull/504 ? Given what it is changing it will solve your problem as well, right?

**Comment by timbonicus** [comment]
#504 doesn't seem related, that just appears to limit the packages checked rather than changing anything about the config validation?

**Comment by Andarist** [comment]
Oh, okay - in a hurry I've assumed that your issue was related to something else and that this could have helped you.

From what I've noticed this call stack was not using the latest `@changesets/config` in your repository and this is a very probable cause that would result in this validation error. So I've prepared a quick PR for you here: https://github.com/backstage/backstage/pull/3577

**Comment by timbonicus** [comment]
Thank you so much, that does the trick! Sorry for the noise, I should have checked the versions in `yarn.lock` 😅
