### ISSUE TITLE
Dependencies are upgraded to new major versions during release

### ISSUE THREAD

**Issue by zkochan** [atlassian/changesets#506]
## Affected Packages

Probably:
* assemble-release-plan
* apply-release-plan

## Problem

Let's say we have a repo with three projects: foo@2.0.0, bar@2.0.0, qar@2.0.0

foo has qar@2.0.0 in the dependencies. Which is the same as in the monorepo.

bar has an older version of qar in dependencies: 1.0.0.

Now if I release a new version of qar (v2.0.1), I only want to get it bumped inside foo. I want bar to keep using qar@1.0.0

However, seems like in some cases qar is bumped in bar as well. The reason is probably that assemble-release-plan is checking the semver ranges when finding dependents but apply-release-plan is not checking the semver ranges.

## Proposed solution

Maybe we should pass more state to apply-release-plan, to prevent it from making breaking/unwanted bumps

**Comment by zkochan** [comment]
I am not sure at the moment how hard it will be to fix this. I will look into it. For us, I think a fast fix would be to only bump version specs if they use the workspace protocol.

**Comment by Andarist** [comment]
To have a flag that would bump only workspace protocols would probably be a good thing. Although I think that depending on the older version of a package (than the one in monorepo) is quite rare - why dont u want to upgrade the dependency?

**Comment by zkochan** [comment]
We have a big monorepo with hundreds of packages and dozens of teams working in that monorepo. A package had some breaking changes and it was not upgraded in all the dependents (a long time ago, probably before we even started using changesets). Ideally it should be upgraded in all dependents to the latest major version. But it would require a lot of effort, so it won't happen soon. For now, we only want to ship a new feature to all the dependents that use the latest version of the package.

I think such an option would work for us and it would probably be even more straighforward than the current behavior.

**Comment by Andarist** [comment]
We need to keep the current behavior as a default but a new option that would allow for your use case sounds OK. We’d appreciate a PR for this 😉

**Comment by zkochan** [comment]
sure, I'll look into it
