### ISSUE TITLE
undefined result on get-github-info call

### ISSUE THREAD

**Issue by tuanddd** [atlassian/changesets#509]
## Affected Packages
get-github-info

## Problem
When configuring changeset, if you pass in the repo name of the wrong format e.g `https://github.com/user/repo` instead of just `user/repo` it will cause the call to the Github API to return `undefined` and therefore causing `Cannot read property 'author' of undefined`. This error message can be misleading/confusing and so I think we need to handle that and show a nicer message.

There is an actual github action with that error of the repo that I'm working on - https://github.com/sajari/sdk-react/runs/1668436313?check_suite_focus=true

## Proposed solution
The solution is to add a more specific/stricter check for `request.repo` field to make sure that it follows the format (`userOrOrg/repoName`)

**Comment by equinusocio** [comment]
I still have this issue. Is there something to do?

**Comment by tuanddd** [comment]
> I still have this issue, but i'm using the correct format "user/repo" for the name . Is there something to do?

Can't really recall since it's been so long 😄, is your repo private or public?

**Comment by equinusocio** [comment]
My [repo is public](https://github.com/equinusocio/scrolles), My configuration is:

```
  "changelog": [
    "@changesets/changelog-github",
    { "repo": "equinusocio/scrolles" }
  ],
```

PS: I add to add a local .env file with the GITHUB_TOKEN and a personal access token.

**Comment by equinusocio** [comment]
Ok nevermind, I tried again and it seems to work, probably was my fault on generating the token or miswrite the repo name dunno.
