### ISSUE TITLE
Minor version of peer package causes release of major version

### ISSUE THREAD

**Issue by FredyC** [atlassian/changesets#524]
## Affected Packages

Here is the specific commit generated by `changeset-release` action.

https://github.com/mobxjs/mobx/pull/2750/commits/c1f30198f2a6674757a7d0c8f8e501c9cdc952dc

## Problem

As you can see, there is a single changeset with `minor` change to the two packages, `mobx` and `mobx-react-lite`. What's unexpected here is the `major` release of `mobx-react-lite` and `mobx-react` in cascade. Even in the changelog, it talks about minor/patch changes so it's rather confusing to the end user.

The `mobx-react-lite` depends on `mobx`, but only as _peerDependency_. In my opinion, it doesn't make much sense to force `major` in such a case. Minor versions are about adding something new, it's not breaking. What is the reasoning here?

## Proposed solution

I think it should release a minor version of `mobx-react-lite` as requested.

We have fixed it manually for now.

**Comment by mitchellhamilton** [comment]
This is currently expected behavior. You can change the behavior of Changesets to what you're probably expecting by adding this to your config:

```json
"___experimentalUnsafeOptions_WILL_CHANGE_IN_PATCH": {
    "onlyUpdatePeerDependentsWhenOutOfRange": true
}
```

See #185 and #383 for more details

**Comment by FredyC** [comment]
Thank you, I've applied configuration and hopefully, it will have the desired effect.
