### ISSUE TITLE
Thoughts on config

### ISSUE THREAD

**Issue by mitchellhamilton** [atlassian/changesets#53]
I want to talk about config.

So, the current format for everything is JS. (except figuring out what the workspaces are which is specified in JSON and isn’t changesets config but it’s very important knowledge to changesets)

I think that has tradeoffs that might not be ideal but also might be the right ones. 

The first thing I want to make sure I'm correct about is that as far as I understand everything with the exception of the `getReleaseLine` and `getDependencyReleaseLine` can be expressed purely in JSON?

## Why I think JSON config is good

- It can be **safely** read in any environment
  - This is a useful thing to build tools on top of that it that run in environments where you can't safely run user code. (i.e. bots and etc. without having to have a ridiculous amount of infrastructure)
    - counterpoint: a big use case for this will be github and because of actions, it'll be practical to run user code safely soon
  - counterpoint: Because of `getReleaseLine` and `getDependencyReleaseLine`, if the config were JSON, you wouldn't be able to do releases without running user code so that would lessen the benefits
- changesets can modify, fix things and etc. in the config because it's JSON
- Probably other things I can't think of 

## Why I think the JS config is good

- Everything can be dynamic so you could share config
  - counterpoint: when will you share config beyond the changelog generation stuff?
  - another counterpoint: where is the dynamicness useful?(with the exception of changelog generation stuff)
- The built in documentation is really really nice
  - counterpoint: it will get out of date as options change and `no documentation > out of date/wrong documentation`
    - counter-counterpoint: how often will options practically change?
- Probably other things I can't think of 

## How I think a JSON config might look

Not if sure if .changeset/config.json or a changeset key in the root level package.json would be better but here's a vague idea of how it could look

```json5
{
  "changesets": {
    // this would be a module id that is resolved relative to where the config file is located
    // so people could write their own changelog generators which export  `getReleaseLine` and `getDependencyReleaseLine`
    // or a company, team or etc. could have a standard one
    "changelogs": "@thinkmill/changelog-generator",
    // there could probably be some tweaking of this,
    // i'm not a big fan of separation of options between version, changeset and publish(also, the naming probably needs to be fixed because of the new command names) how it is right now because it means having config that goes through multiple parts of the system is strange but also I see how it's nice in some cases
    ...theRestOfTheConfigOptionsLikeTheyAre
  }
}
```

(this isn't meant to be "I think this is what we should do" but more "I think the current approach and another approach both have different trade offs and we should discuss about which one is better for changesets")

**Comment by Noviny** [comment]
> everything with the exception of the getReleaseLine and getDependencyReleaseLine can be expressed purely in JSON

True dat

> how often will options practically change?

Options should basically never change. You're right that the inline docs will get out of date on the rare occasion it happens though.

> no documentation > out of date/wrong documentation

This is pretty accurate, and at very least we should add in a mitigation here that adds the version number of changesets when the config was generated, so people have a way to diff that.

One of the primary reasons we write out the config is that getting things like the releaseLine to be what you want is hard without context - adding packages/plugins for changelog generation would solve that.

>     "changelogs": "@thinkmill/changelog-generator",

I think overall moving to having changelog generationg packages would be good, because then it becomes easy to set up how changelogs look/feel, with a collection of ones that are pre-defined instead of making everyone do this themselves. (there are only about 3 or 4 formats we use anyway). This would also mean that the `get-github-info` package 

> the naming probably needs to be fixed

Hm, yeah. 2.0 here we come. All these changes probably lead to a 2.0 release.

> separation of options between version, changeset and publish

I like this separation 1) because it gives more information on when this is going to be applied, and 2) allows splitting up things like `commit` so you set it explicitly for adding a changeset and for versioning separately. That can of course be achieved by `commit: true` and `commit: ["add", "bump"]` both being accepted in json.


> you wouldn't be able to do releases without running user code so that would lessen the benefits

This is probably the biggest reason to not switch. If we still require executing user code, and may still ask people to make async functions, I like it being `.js` so that's more clearly communicated.

---

Aside, thanks for writing this up. It's nice to have someone questioning assumptions that have been around for a while with changesets.

---

I think there's a bunch of steps that can be done towards this, with step 1 being:

Ship the most common `changelog` patterns as packages, and document how to consume them

With step 2 leaning towards new ways to consume things.

**Comment by mitchellhamilton** [comment]
> I like this separation 1) because it gives more information on when this is going to be applied, and 2) allows splitting up things like commit so you set it explicitly for adding a changeset and for versioning separately. That can of course be achieved by commit: true and commit: ["add", "bump"] both being accepted in json.

My fear is that the separation is already inaccurate and it could get more inaccurate. For example, with versionOptions and status, since versionOptions is used by status and it accepts a commit option, does that mean that status will commit stuff?

Also, if the bump all the dependents even when they're in range mode existed, where would that option go? Would it be in changesetOptions and it would add all the dependents to the changeset? If so, what about #40, it would mean that the bump command needs to know about that option as well so would it read changesetOptions?

Similarly with pre-release, that would use versionOptions right?

(I might be thinking too literally about the mapping between commands to config options but I think that was intended with the naming of the options + commands?)

The main thing I'm trying to say is that separation seems cool and has some advantages and it might even be the right trade off to make here but often things are related in subtle ways so rather than separating things, you get the appearance of separation and then explaining everything gets more complex because you're going against people's intuition of "these things are separated by commands so each set of options relates to a command" and you have to go "yes, expect for these cases".

Of course, I might be thinking too much about little technicalities ¯\\\_(ツ)_/¯

> This is probably the biggest reason to not switch. If we still require executing user code, and may still ask people to make async functions, I like it being .js so that's more clearly communicated.

I don't 100% get this. There are numerous examples of tools executing user code and specifying config in JSON(off the top of my head, I can think of Babel and Parcel but there are probably others), why does having the config in a js file more clearly communicate that user code is executed than a path to a module?

**Comment by Noviny** [comment]
I guess the big one is all the extra data the functions often need. The main reason to customise this is to provide links to github/bitbucket for the commits the changeset belongs to, rather than just having a git hash.

You could do json config of:

```
"changelogs": ["@thinkmill/sweet-changelogs", "https://github.com/changesets"]
```

to pass in the variable, but most implementations need some extra detail, maybe more. I guess like I just showed, there are ways to do this (and this bit of info *can* be inferred from a package.json with a repository field).

The original reasoning was if this bit of config **has** to be dynamic, then there's no harm in making the rest of it dynamic.

**Comment by mitchellhamilton** [comment]
A reason why I think JSON config would be good that I think might decide it: it would be possible to know what packages will be published and even technically do a release (with the very very notable exception of changelogs) without executing user code. I think the being able to know what packages will be published would be really helpful so we could surface that info in the changeset bot or elsewhere. (I'm thinking maybe it could be in a`<details><summary>` so the data is there but it's not shown by default and doesn't take up much space)

Also, this is how I think a JSON config could be expressed in complete form.
```ts
type Config = {
  // ModulePath would be path to a module that exports either getReleaseLine and getDependencyReleaseLine or a function that accepts the JSONValue and returns getReleaseLine and getDependencyReleaseLine
  changelog: false | ModulePath | [ModulePath, JSONValue],
  commit:
    | boolean
    | "skip-ci"
    | { add: boolean | "skip-ci", bump: boolean | "skip-ci" },
  linked: Array<Array<PackageName>>,
  public: boolean
};
```

Anecdotal side note: this config feels so small, when I think about changet's config, I always think of it as this big thing, maybe that's because of all the comments but it's interesting to see how few options there need to be to express the whole config.

**Comment by mitchellhamilton** [comment]
So I thought I commented on this issue on Friday but apparently I didn't so anyway, here are the things we concluded with.

The big thing is that the config is going to be JSON.

This is the shape that the config will be represented internally as when we're passing it around to functions:

```tsx
type ModulePath = string;
type JSONValue = any;
type PackageName = string;

type Config = {
  changelog: false | [ModulePath, JSONValue],
  commit: boolean,
  linked: Array<Array<PackageName>>,
  access: "public" | "private"
};
```

The config on disk as JSON would be a type of
```tsx
type Config = {
  $schema: "some-url-to-a-schema",
  changelog?: false | ModulePath | [ModulePath, JSONValue],
  commit?: boolean,
  linked?: Array<Array<PackageName>>,
  access?: "public" | "private"
}
```

The default value/what we would write with the init command:

```json
{
  "$schema": "some-url-to-a-schema",
  "changelog": "@changelogs/cli/some-entrypoint-for-this",
  "commit": false,
  "access": "private",
  "linked": [[]]
}
```

This is how the config could be expressed in [JSON Schema](http://json-schema.org)

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "enum": ["some-url-to-a-schema"],
      "description": "The schema to verify this document against."
    },
    "changelog": {
      "anyOf": [
        {
          "type": "array",
          "items": [
            {
              "type": "string",
              "title": "Changelog Generator Path"
            },
            { "title": "Changelog Generator Options" }
          ],
          "minItems": 2
        },
        {
          "enum": [false],
          "type": "boolean"
        },
        {
          "type": "string",
          "title": "Changelog Generator Path"
        }
      ],
      "description": "The configuration for changelog generators."
    },
    "linked": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "description": "Packages that should be linked together so when they are being released, they will be released at the same version. If you've used Lerna to version packages before, this is very similar."
    },
    "commit": {
      "type": "boolean",
      "description": "Determines whether changesets should commit the results of the add and bump command"
    },
    "access": {
      "enum": ["private", "public"],
      "type": "string",
      "description": "Determines whether changesets should publish packages to the registry publicly or privately"
    }
  },
  "required": ["$schema"]
}
```
