### ISSUE TITLE
[question]: Why would tags not be generated?

### ISSUE THREAD

**Issue by pngwn** [atlassian/changesets#543]
We have been using changesets to manage [svelte-kit](https://github.com/sveltejs/kit)'s versioning but we have noticed that no tags are being generated/ pushed in the repo itself (things are being tagged [in npm](https://www.npmjs.com/package/@sveltejs/kit?activeTab=versions)). We also have this issue in one or two other repos.

We are currently using pre-release mode.

Do you know why tags would not get generated? This is preventing the github action from generating github 'releases' as well.

**Comment by Andarist** [comment]
Well, you don't call to changeset when publishing:
https://github.com/sveltejs/kit/blob/d0a701904869ababb11c559bd033ecd2599c4af4/.github/workflows/release.yml#L31-L32

and our GitHub action relies on the stdout for tagging and creating releases

**Comment by pngwn** [comment]
Yup, I totally missed that. 

Apologies and thanks for the response!
