### ISSUE TITLE
404 error while publishing packages that already exist

### ISSUE THREAD

**Issue by ianstormtaylor** [atlassian/changesets#550]
I'm trying to get Changesets setup for [Slate](https://github.com/ianstormtaylor/slate) using a `--snapshot` release on a `dev` tag, but running in to problems.

For some reason it's failing with a `404` not finding the existing packages? Even though the `npm info` lines clearly succeeded it still fails later on. The lines in question:

```
🦋  error  'slate@0.0.0-2021230191014' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error an error occurred while publishing slate-react: E404 Not Found - PUT https://registry.npmjs.org/slate-react - Not found 
🦋  slate@0.0.0-2021230191014
```

And the full log ([link to action](https://github.com/ianstormtaylor/slate/runs/2230790104?check_suite_focus=true)):

```
Run yarn changeset version --snapshot
  yarn changeset version --snapshot
  yarn changeset publish --tag dev
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    NPM_TOKEN: ***
    NODE_AUTH_TOKEN: ***
yarn run v1.22.5
$ /home/runner/work/slate/slate/node_modules/.bin/changeset version --snapshot
🦋  All files have been updated. Review them and commit at your leisure
Done in 0.54s.
yarn run v1.22.5
$ /home/runner/work/slate/slate/node_modules/.bin/changeset publish --tag dev
Package "slate-packages" must depend on the current version of "slate": "0.0.0-2021230191014" vs "*"
Package "slate-packages" must depend on the current version of "slate-history": "0.0.0-2021230191014" vs "*"
Package "slate-packages" must depend on the current version of "slate-hyperscript": "0.0.0-2021230191014" vs "*"
Package "slate-packages" must depend on the current version of "slate-react": "0.0.0-2021230191014" vs "*"
🦋  warn ===============================IMPORTANT!===============================
🦋  warn Packages will be released under the dev tag
🦋  warn ----------------------------------------------------------------------
🦋  info npm info slate
🦋  info npm info slate-history
🦋  info npm info slate-hyperscript
🦋  info npm info slate-react
🦋  info slate is being published because our local version (0.0.0-2021230191014) has not been published on npm
🦋  info slate-history is being published because our local version (0.0.0-2021230191014) has not been published on npm
🦋  info slate-hyperscript is being published because our local version (0.0.0-2021230191014) has not been published on npm
🦋  info slate-react is being published because our local version (0.0.0-2021230191014) has not been published on npm
🦋  info Publishing "slate" at "0.0.0-2021230191014"
🦋  info Publishing "slate-history" at "0.0.0-2021230191014"
🦋  info Publishing "slate-hyperscript" at "0.0.0-2021230191014"
🦋  info Publishing "slate-react" at "0.0.0-2021230191014"
🦋  error an error occurred while publishing slate-history: E404 Not Found - PUT https://registry.npmjs.org/slate-history - Not found 
🦋  error 
🦋  error  'slate-history@0.0.0-2021230191014' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error an error occurred while publishing slate-hyperscript: E404 Not Found - PUT https://registry.npmjs.org/slate-hyperscript - Not found 
🦋  error 
🦋  error  'slate-hyperscript@0.0.0-2021230191014' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error an error occurred while publishing slate: E404 Not Found - PUT https://registry.npmjs.org/slate - Not found 
🦋  error 
🦋  error  'slate@0.0.0-2021230191014' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error an error occurred while publishing slate-react: E404 Not Found - PUT https://registry.npmjs.org/slate-react - Not found 
🦋  slate@0.0.0-2021230191014
🦋  error 
🦋  slate-history@0.0.0-2021230191014
🦋  error  'slate-react@0.0.0-2021230191014' is not in the npm registry.
🦋  error You should bug the author to publish it (or use the name yourself!)
🦋  error 
🦋  error Note that you can also install from a
🦋  error tarball, folder, http url, or git url.
🦋  error packages failed to publish:
🦋  slate-hyperscript@0.0.0-2021230191014
🦋  slate-react@0.0.0-2021230191014
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by ianstormtaylor** [comment]
For any others running into this...

- Although it shows a `404` this is actually a permissions error on the NPM side of things, meaning something in the authentication isn't properly working. (https://github.com/npm/cli/issues/1637)
- Turns out that although the logs were printing that it was using `https://registry.npmjs.org`, you still need to manually set the `registry_url` key in the `actions/setup-node` action for this to work. (https://github.com/actions/setup-node/issues/82)

Once you fix those two things it works just fine.

**Comment by estrattonbailey** [comment]
Hey y'all 👋  I'm having the same issue and I think I'm stumped. I've tried everything suggested here and in the other threads linked above but I still get the 404 PUT error, even for non-scoped packages i.e. `presta`.

[Here's an example](https://github.com/sure-thing/presta/runs/3012096531?check_suite_focus=true#step:12:46) of the build logs, and here's [my Github action.](https://github.com/sure-thing/presta/blob/master/.github/workflows/cd.yml) FWIW I also tried combinations of disabling 2FA and using a "publish" npm token for additional permissions, but no dice, so I'm back to a normal "automation" token workflow.

I've been referencing other projects like tinyhttp (and Slate), but looks like they've been having the [same issues](https://github.com/tinyhttp/tinyhttp/runs/3011980371?check_suite_focus=true#step:8:295).

Seems like we're all super close to getting this working — maybe there's something simple I can help debug? Unsure where to start 🤔

**Comment by estrattonbailey** [comment]
Just following up 👋 still running into this (on a new project this time, just set everything up). Looks like tinyhttp is still having the same issues as well — see issue in the Changesets action https://github.com/changesets/action/issues/98

I've tried some of the suggestions of creating my own `.npmrc` as well, but no luck. Seems like the outlier in my case is my usage of `pnpm`, could that be the culprit?

So sorry to ping you directly, @Andarist, I know you must have a million notifications. Any ideas?

**Comment by estrattonbailey** [comment]
Following up: I was able to get this working, see https://github.com/changesets/action/issues/98#issuecomment-917292485

**Comment by Andarist** [comment]
I've already posted this in the mentioned GitHub action's issue but since the last messages here refer to this problem I have thought that it might be worth mentioning it here as well.

I've created a PR that should, hopefully, help with @estrattonbailey's case here: https://github.com/changesets/action/pull/110
