### ISSUE TITLE
[changesets/action] Incorrect changeset detection on first PR to add changeset support

### ISSUE THREAD

**Issue by JounQin** [atlassian/changesets#578]
## Affected Packages

`changesets/action`

## Problem

![image](https://user-images.githubusercontent.com/8336744/116030428-16062380-a68e-11eb-9302-79ec1f8d16c5.png)

Shouldn't is tell that no changelog detected to release?

**Comment by Andarist** [comment]
> Shouldn't is tell that no changelog detected to release?

It should.

Could you share a repository in which this has happened or prepare a runnable repro case for this?

**Comment by JounQin** [comment]
https://github.com/rx-ts/synckit/pull/1#issuecomment-826491268

The PR has been merged, you can check the comment history.

**Comment by JounQin** [comment]
@Andarist 

And https://github.com/rx-ts/markuplint-sync/pull/1#issuecomment-827751235

I haven't added any changelog files yet.

**Comment by Andarist** [comment]
Thank you for pointing me out to those PRs. This should be an easy fix in this filter:
https://github.com/changesets/bot/blob/54d670e6ec22887c120c3272557c91193d03f274/index.ts#L125

Gonna handle this later today.

**Comment by Andarist** [comment]
I've prepared a fix here: https://github.com/changesets/bot/pull/31 . Since the fix is the other repository I'm going to close this issue here.

**Comment by JounQin** [comment]
@Andarist I don't know whether your fix related, but it shows no changeset found even if I've added.

https://github.com/rx-ts/markuplint/pull/16#issuecomment-833485371

![image](https://user-images.githubusercontent.com/8336744/117299548-424e4b00-aeab-11eb-9c44-04e23161d633.png)

![image](https://user-images.githubusercontent.com/8336744/117299569-48442c00-aeab-11eb-9af4-50e5caa9ef1a.png)
