### ISSUE TITLE
How can I specify the folder to be published?

### ISSUE THREAD

**Issue by JounQin** [atlassian/changesets#605]
## Affected Packages

`@changesets/cli`

## Problem

For Angular packages, we're using [ng-packagr](https://github.com/ng-packagr/ng-packagr) for building, and usually it will generate a clean folder `release`, for example, which includes `package.json` inside, so we want to publish the `release` fold instead of the root folder.

What means we want `npm publish ./release` instead.

## Proposed solution

A new option to specify which folder should be published.

For monorepos, we want to publish `<root>/packages/pkgA/release` instead of `<root>/packages/pkgA`.

---

Or, is there any workaround for now?

**Comment by Andarist** [comment]
Could you check this this satisfies your use case: https://github.com/atlassian/changesets/pull/428 ?

**Comment by JounQin** [comment]
Thanks, it seems nice, although I didn't find it in the document.

https://github.com/atlassian/changesets/blob/main/docs/config-file-options.md
