### ISSUE TITLE
changeset version not bumping dependents for prerelease changes

### ISSUE THREAD

**Issue by justinfagnani** [atlassian/changesets#606]
## Affected Packages

?

## Problem

When using prerelease mode I expected dependents to have their version constraints updated during `changeset version` as mentioned here: https://github.com/atlassian/changesets/blob/main/docs/prereleases.md

> An important note is that this will bump dependent packages that wouldn't be bumped in normal releases because prerelease versions are not satisfied by most semver ranges.(e.g. ^5.0.0 is not satisfied by 5.1.0-next.0)

This isn't happening for me. I'm running this sequence:

```
$ npm run changeset pre enter rc
$ npm run changeset add
# choose to include pkg-a
# choose pkg-a as major change
# Add description
$ npm run changeset version
Only pkg-a's package.json is updated, not other packages that use it.
```

## Proposed solution

The docs seems to describe the behavior we need. Maybe this is a regression?

**Comment by Andarist** [comment]
Could you try to write a test case for your exact scenario? 

We have a basic test that verifies this behavior and it seems to be very similar to what you describe. Even though only `pkg-b` has a changeset created for it the `pkg-a` is bumped as well and its `dependencies` are adjusted accordingly:
https://github.com/atlassian/changesets/blob/c426035565cfac518238c8bf32f3c496c66c0657/packages/cli/src/commands/version/version.test.ts#L532-L534

**Comment by Andarist** [comment]
A runnable repro case has not been provided. I'm going to close this issue for housekeeping purposes as I must assume this is not a problem anymore. If you manage to create a repro case then please open a new issue with the repro case attached to it.
