### ISSUE TITLE
`changeset version --ignore` work not normal

### ISSUE THREAD

**Issue by fireairforce** [atlassian/changesets#631]
## Affected Packages
For instance, i have monorepo project which have package A and B, if A depends on B, i use changeset to generate B's changeset file, when i use `changeset version --ignore A`, the dependencies B in A will still change its version. 

## Problem

As Affected Packages description.

## Proposed solution

I hope `--ignore` can totally ignore A's change, even A depends on B, i just want to update B but not A...

**Comment by Andarist** [comment]
Changesets have some opinions about how it works and how it updates the packages etc. One of the main principles is that we favor safety whenever possible (and reasonable). Imagine this situation:

1. you release B without changing the dependency range in A
2. you develop A, starting to rely on something that has been recently added/fixed/whatever in B (you are within a monorepo after all, so u have a direct access to the most fresh code for each package at all times)
3. you release A, the dependency range for B stays untouched, and thus you are releasing for your consumers something that is partially broken

Of course, we could flip things and update dependency ranges when versioning dependants (whereas we mostly do that at the moment when versioning dependencies). I don't see a strong reason to do this though as you'd end up with mismatched dependency ranges and current versions of packages - which usually is a sign that a monorepo is in some kind of an inconsistent state.

I'm going to close this as part of cleaning up issues for housekeeping purposes. However, please don't hesitate to respond back here or in another issue - I will reopen this if you feel like the issue has not been addressed in full.
