### ISSUE TITLE
Add author to changelog

### ISSUE THREAD

**Issue by 07akioni** [atlassian/changesets#632]
## Affected Packages

`@changeset/changelog-git`

## Problem

Currently only `commit` hash is exposed. However I want to add author info (maybe email or username)  to the changelog so that we can know who made the change directly (without checking commit log).

## Proposed solution

Expose author info from `getReleaseLine` or just make `changelog-git` customizable with some options.

**Comment by Andarist** [comment]
Everyone wants slightly different things to be included in their changelogs - this is why you can easily create "changelog generators" to adjust the output however you want. Notice how, for example, `urql` does this with a local changelog generator: https://github.com/FormidableLabs/urql/blob/83f515539b283881aa79a8609e1fa816dc750039/.changeset/config.json#L3
