### ISSUE TITLE
changeset not working on pnpm workspace exclude rules

### ISSUE THREAD

**Issue by fz6m** [atlassian/changesets#661]
## Affected Packages

pkg: git
pkg: apply-release-plan
pkg: release-utils
pkg: get-dependents-graph
pkg: pre
pkg: config
pkg: cli
pkg: assemble-release-plan
pkg: get-release-plan

## Problem

`pnpm-workspace.yaml`:

```yml
packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
```

project:

```yml
  - test
    - packages
      - pkg-1   # (need)
      - pkg-2  # (need)
      - test   # (not need)
    - pnpm-workspace.yaml
```

if project absolute cwd path matches the pnpm workspace exclude rule, `getPackages` won't get any packages. 

## Proposed solution

fixed in https://github.com/Thinkmill/manypkg/pull/122 . 

After the `@manypkg` is released, changeset dependencies need upgrade

**Comment by Andarist** [comment]
Thank you for the fix, we'll have to await @mitchellhamilton's approval and the downstream release
