### ISSUE TITLE
Multiple versions of the same package issue

### ISSUE THREAD

**Issue by imike57** [atlassian/changesets#679]
Hi,

Some package manager like ppm allow to have a package with multiple versions. Which can be useful when you want to have several packages which are dependencies of this one, but you don't want to migrate all to a new version. 

For example 

Package A 1.0.0 is dependencies of Package B, C, D, ...

Package A got a new version 2.0.0

I have to make some changes in Package B, C, D,... to make them compatible with, but I don't want this new version to break my whole build if I don't migrate all of these or if I want keep only some compatible with Package A 1.0.0. 

So ppm allows to keep Package A 1.0.0 and Package A 2.0.0 on the same repo. And each of my other packages can have one or other as a dependency... 

The issue, is that look not compatible with "changesets". 

If I have two packages with the same name, `pnpm changeset` will found them.. If I select both, it will ask only for one of them if I want to bump. 

Also, if these both packages have another package as dependency, and I update this one, so both of them should update the package.json, but only one is updating. Ignore one is something that could be required, as if I keep a previous version, it should no more be modified. But it's probably something that we should be able to ignore as desired. 

Do you know if there is an optimal solution to work with "changesets", a monorepo and multiple package versions?

**Comment by Andarist** [comment]
Do you want to keep both release lines active? As in - you would like to manage releases for both versions of this package using Changesets? Or is the "old" version frozen?

**Comment by imike57** [comment]
The old version should be frozen.

**Comment by Andarist** [comment]
Do you even need to keep the old version in your current branch then? If you would:
1. remove it
2. use workspace protocol for the new version in packages that depend on it
3. and use no workspace protocol in the packages that depend on the old one
4. And configure Changesets to use `bumpVersionsWithWorkspaceProtocolOnly`

Then it should work fine, see https://github.com/atlassian/changesets/pull/507

**Comment by imike57** [comment]
thank's @Andarist , I will look around this idea.
