### ISSUE TITLE
Add a link to create a changeset from the changeset bot comment

### ISSUE THREAD

**Issue by mitchellhamilton** [atlassian/changesets#71]
~~Open questions:~~
- ~~Should maintainers write custom changeset summaries in the syntax or use the PR name?~~
- ~~What should the syntax be?~~
- ~~Should we list the changed packages or something in the you have/don't have a changeset message?~~

The plan is now to add a link to the changeset bot comment with a pre-filled filename so a maintainer can write a changeset.

**Comment by Noviny** [comment]
I personally want to make everyone always type a summary - copy/pasting is easy, and I can see people not wanting to edit the pr title, or wanting a longer changeset message

**Comment by mitchellhamilton** [comment]
Any ideas on what the syntax should be?

**Comment by mitchellhamilton** [comment]
This is what I'm thinking of
```
```changeset
- @changesets/cli@major
---
My cool summary here.
(this text is here for escaping, it wouldn't be here in the real thing)```
```

**Comment by Noviny** [comment]
So, basically an code block with `changeset` in the language slot, a dash list of packageName@bumpType, and then every below a break-line is the summary?

I think it looks good.

Second questionish thing, how does this work in failure cases (name a package that isn't in the repo for example (I'd assume mostly typos))? Otherwise failing to commit. Also making sure it's responsive enough. I assume you see the new commit - is that enough?

**Comment by mitchellhamilton** [comment]
> So, basically an code block with changeset in the language slot, a dash list of packageName@bumpType, and then every below a break-line is the summary?

Yes.

> Second questionish thing, how does this work in failure cases (name a package that isn't in the repo for example (I'd assume mostly typos))?

I was thinking of making the bot write a comment if something fails and we handle common users errors with custom messages and for any error that can't be recognised, we write a comment saying "an internal error occured" (I don't want to make it expose the errors directly because of the possibility of exposing secrets)

**Comment by Noviny** [comment]
With v2 changeset format, do we still want/need this? You can just add a `.md` file manually and get the result.

**Comment by mitchellhamilton** [comment]
https://github.com/atlassian/changesets/pull/83#issuecomment-504635703 is what the plan is now

We'll add a link to the changeset bot comment with a pre-filled filename so a maintainer can write a changeset.

**Comment by Noviny** [comment]
I believe this is now done?

**Comment by mitchellhamilton** [comment]
Yes! 🎉
