### ISSUE TITLE
Execute default $EDITOR when empty summary given

### ISSUE THREAD

**Issue by jesstelford** [atlassian/changesets#79]
Doing a `git commit` without a message will;
- create a temporary file in `/tmp`
- execute `sh -c $EDITOR /tmp/<path-to-tmp-file>`
- wait until the $EDITOR process exits
- use the contents of `/tmp/<path-to-tmp-file>` as the commit message

I'd love to have the same thing for changesets :+1:

**Comment by Andarist** [comment]
I believe this has been implemented some time ago: https://github.com/atlassian/changesets/blob/6353abf925d13c41feb1884124ddb5edc8c33555/packages/cli/src/commands/add/createChangeset.ts#L230-L232
