### ISSUE TITLE
Prereleases

### ISSUE THREAD

**Issue by mitchellhamilton** [atlassian/changesets#9]
A lot of large open source projects need to do prereleases to share things with the community before releases so they can provide feedback without having to do the real release and then having to do lots of major versions when they inevitably need to change things.

The way I'm thinking this would work is that you would have all of your changesets and when you run something like `build-releases version-packages --prerelease=beta`, the tool would calculate all of the versions and then append something like `-beta.0` to them and write all the versions. I'm thinking choosing the npm dist tag to publish to should probably be something that users handle themselves by using the publishConfig field that npm looks at in package.jsons.

Maybe the changesets that are used in a prerelease could be kept in the file system still(in another directory?) so that for the final release, they could all be used to create the changelog entry for the final version.

I'm not totally sure about how specifically all of this should work and this has a bunch of open questions but I think the general idea would be good to have.

(This isn't a need to have for emotion to use it right now but would likely be necessary in the future when we do the next major version but that likely won't be for a couple months I'm guessing)

**Comment by Noviny** [comment]
> build-releases version-packages --prerelease=beta

good needed feature

> Maybe the changesets that are used in a prerelease could be kept in the file system

Hm. The unanswered q here is around workflow

- does the branch that releases betas end up in master?
- do you update the changelog?
  - if yes to both of the above, can the changeset tool collapse entries in a changelog upon release so they are not duplicated?

If the branch never ends up in master, removing changesets doesn't matter.
If you are writing to changelogs, you probably want to remove changesets - automating joining beta changelog entries may be fraught though.

**Comment by mitchellhamilton** [comment]
> does the branch that releases betas end up in master?

I think there are use cases for having it in master and not having it in master. For example, you’re working on a sizeable minor version of a group of packages, you do it on a branch so you can keep updating and publishing master but another example is that you are working on a really big major and you don’t want to keep on doing releases of the stable version because it’s hurting productivity working on the new version too much so you want to have the new version that you’re working which you’re doing prereleases for on master. 


> do you update the changelog?

I would say yes, especially because you could do really nice things like have changelog entries for each prerelease, then for the actual release, you could have two entries, one for people updating from a prerelease which includes the changes from the last prerelease to the stable release and another for updating from the previous stable release which includes all the changes from all the prereleases and from the last prerelease to the stable version.

> If you are writing to changelogs, you probably want to remove changesets - automating joining beta changelog entries may be fraught though.

Yeah, I feel like automatically joining the changelogs entries would be especially problematic because of how customizable they can be.

My thinking is that when you do a prerelease, build-releases could look for changesets in the .changeset directory like it does right now and then move the changesets into a folder inside that named something like `prereleased-changesets` (there's probably a better name for that) and then when stable releases happen, build-releases looks for changesets in .changset and prereleased-changesets and handles the different directories specially in terms of changelogs like I mentioned above.

**Comment by Noviny** [comment]
## Current thoughts on how to implement pre-releases:

```
changeset bump --pre-release=alpha
```

- Reads in current changesets
- Updates by bump type and appends the pre-release type, so `1.1.0` with `minor` becomes `1.2.0.alpha.0`
- writes `.changeset/prereleases` file

`.changeset/prereleases.json` contains approximately:

```
{
  "originalVersions": [...{  "name", "version"  }],
 "changesets: [...changesetHash],
}
```

If you run `changeset bump` without specifying a pre-release it will stop and ask you if you want to release as another pre, or do a proper release.

### For a proper release

- I am not sure what to do with changelogs. The `pre` info should likely be scraped, but doing so is presumably never safe.
- Revert all packages to their original versions
- Run bump, as normal
- remove `prereleases.json`

### For another pre-release

- When getting changesets, filter out all changesets in `prereleases.json.changesets`
- Use `originalVersions` to get the new version
- Compare the new version with the current pre-release in the `package.json`. If the new version is higher, write it to the package.json as eg. `2.0.0.alpha.0`, otherwise, iterate the number at the end up by one.
- Write new changesets to `prereleases.json`



### Concerns

- Expands the changeset spec (pre-releases necessarily do this)
- I haven't really solved what to do with changelogs through this whole thing

### Notes

- The alternate suggestion was to move pre-released changesets into a new directory. I'm suggesting a single file to store information partly so we have to change less, and partly so we have somewhere to store the original versions.
- I've assumed that knowing how many pre-releases you have done isn't important, nor what all of them are.

**Comment by mitchellhamilton** [comment]
> `1.2.0.alpha.0`

`1.2.0.alpha.0` should be `1.2.0-alpha.0` right? [That's what semver says.](https://semver.org/#spec-item-9)


> The pre info should likely be scraped, but doing so is presumably never safe.

By pre info, do you mean changelog entries for prereleases?

> `...changesetHash`

What is `changesetHash`?

**Comment by Noviny** [comment]
Yes 1.2.0-alpha, not what I wrote.

Pre info is prerelease changelog entries.

The changesetHash is probably more correctly title the changeSetDir, to use it as identifying info.

**Comment by mitchellhamilton** [comment]
> The changesetHash is probably more correctly title the changeSetDir, to use it as identifying info.

Ahhhhhh, I get it now, I didn't read the `filter out all changesets in prereleases.json.changesets` part.

I like all of this very very very strongly.

> The alternate suggestion was to move pre-released changesets into a new directory. I'm suggesting a single file to store information partly so we have to change less, and partly so we have somewhere to store the original versions.

Very good idea, a single file is much better.

> I am not sure what to do with changelogs. The pre info should likely be scraped, but doing so is presumably never safe.

I **don't** think pre info should be scrapped. If people don't want that info to be scrapped then they can do pre-releases in another branch that is never merged into master. 

How I think changelogs should work:

When doing a pre-release, changelogs essentially work just like they do with normal releases.

When doing a proper release, write an entry that looks like this:

```markdown
## THE_NEW_PROPER_VERSION

### Since LAST_STABLE_VERSION

ENTRIES_SINCE_LAST_PROPER_VERSION

### Since  LAST_PRE_RELEASE

ENTRIES_SINCE_LAST_PRE_RELEASE
```
---
How should publishing work for pre-releases wrt npm dist tags?

I think the behavior people will want is `alpha` in `--pre-release=alpha` is the dist tag.

Another question then: how does the release command know what dist tag to publish to?

Supporting  `--pre-release`  in the `release` command would work but I feel like that kind of sucks and would result in people accidentally publishing pre-releases to `latest` when they forget to use the option in the `release` command.

One option would be writing the the pre-release tag to `prereleases.json`.

One thing I kind of prefer though(I don't feel that strongly about it, just an idea) is setting the prerelease tag in the config file. When you're not doing pre-releases, it could be set to `latest` since that's the default npm dist tag. The option could probably just be named like `tag` or something.

---

Edge case: what if I've done some pre-releases with one pre-release tag and then I change the pre-release tag to a different one?

**Comment by Noviny** [comment]
#84 drastically simplifies this, so we are going to put this on hold until that is complete.
