### ISSUE TITLE
Should we remove `commit: true` as an option?

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#90]
Currently the `commit` option is the reason we separate config by command - which we would like to stop doing (it would greatly simplify the config).

As part of this, I want to talk about where changesets intersects with `git` - and should it?

Currently, we intersect with git in:

- Committing changesets + committing bumps
- writing changelogs (we default grab and hand back commit info)
- `status` has `--since-master` option, which will make it care about git

We've said in the past that we don't want changesets to be tied to git, so what happens if we don't tie it to git?

- Committing bumps is still easy enough to do in CI when you want to commit them
- Committing changesets become more likely to be missed - you can add a changeset, push changes, and have forgotten to add the files - this seems a weak argument to me.
- Writing changelogs having access to the git hash helps out a lot with writing changelog messages. Could the logic that fetches it be split into an optional library, similar to how fetching info from github is split out?
- The status command doing this still seems fine.

**Comment by mitchellhamilton** [comment]
> We've said in the past that we don't want changesets to be tied to git

Where was this said before? I vaguely agree that not tying changesets to git is a good thing but I'd be interested to hear some reasons behind it.

More things for the list of places where we use git:
- Getting the changed packages when creating a changeset
- Creating tags in `release` (this might be hidden behind bolt?)

> - Committing bumps is still easy enough to do in CI when you want to commit them
> - Committing changesets become more likely to be missed - you can add a changeset, push changes, and have forgotten to add the files - this seems a weak argument to me.

👍 

> Writing changelogs having access to the git hash helps out a lot with writing changelog messages. Could the logic that fetches it be split into an optional library, similar to how fetching info from github is split out?

I think this is okay on the condition that we have the changelog packages stuff we've been talking about exists because people having to write even more complex changelog entry generator things would be annoying. One thing that we'd have to make sure of if we did this is only deleting the changesets after the changelog entries are generated.

**Comment by Noviny** [comment]
> Where was this said before?

Good callout. This has come up in some internal brainstorming when presenting changesets. When we went to move it into Keystone, it always committed, and not committing was added as a 'feature' for keystone.

Since then, it's been sort-of an ideology, and sort-of not. There are some aspects of changesets that clearly want info from git, or don't work nearly as well, but at a conceptual level, changesets are interesting because they are just writing and consuming files.

As such, changesets baking itself on top of git is more an accident than a decision, and getting clear separations around it would be nice. That or this exploration leads us to more clearly scope *where* changesets touch git, and refuse to budge on it touching in other places.

> Getting the changed packages when creating a changeset

This, to me, is the most compelling use of git. It's the same as the status usage, effectively (get something since master). We can probably include this, but not fail the command if we can't find this info, which I believe it currently does.

I think the standard here should be 'works well with git', but not 'breaks without git'

**Comment by mitchellhamilton** [comment]
> I think the standard here should be 'works well with git', but not 'breaks without git'

I like this a lot.

So the only places that changesets itself will care about git are:

- `add` for getting the changed packages
- `status` for `--since-master`

And there will be a helper for getting the commit from a changeset. (I assume we'll pass the name of the changeset in then?) The one thing that slightly worries me is the release line generators caring about things that exist in the file system but that's probably okay.

If that's correct then I think I'm happy with this.

**Comment by mitchellhamilton** [comment]
Just a little thing on this: I just ran `changeset add` in a directory without a git repo and it failed
```
❯ yarn changeset
yarn run v1.16.0
$ /Users/mitchellhamilton/projects/changesets-test-thing/node_modules/.bin/changeset
Error: fatal: not a git repository (or any of the parent directories): .git

    at ChildProcess.child.on.code (/Users/mitchellhamilton/projects/changesets-test-thing/node_modules/projector-spawn/index.js:53:16)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
error Command failed with exit code 1.
```

**Comment by Noviny** [comment]
Gross. This is probably a separate issue. We're probably not going to remove git from 'add' - issue should probably be 'catch errors from git being absent and continue on as best possible'

**Comment by mitchellhamilton** [comment]
👍 I'll open another issue.

**Comment by Noviny** [comment]
@mitchellhamilton I think removing this is going to be more pain than it's worth - probably going to close this as discussion ended, but work on isolating the code that does the git adding etc into its own very clearly distinct function, not spread through the main workflow, unless you have strong opinions against.

**Comment by mitchellhamilton** [comment]
👍 to that, my main opinion would be do the thing that is easiest/won't slow down getting v2 done(whether that's isolating the logic or not) for now and any refactoring we want to do can come later.
