### ISSUE TITLE
Add 'select all' for major  and 'minor' lists, not just initial package lists 

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#96]
When selecting pacakge for `major` and `minor` bumps from list, also display `all changed` and `all unchanged`, in similar way to initial package select, to make mass releases easier.

@mitchellhamilton if you don't have any args against, I'll mark this is a good first issue and send it.

**Comment by mitchellhamilton** [comment]
Assuming you mean a section thing like the changed and unchanged packages thing then I’m good with it.

**Comment by Noviny** [comment]
Yeah, that.

**Comment by tarang9211** [comment]
I've already started this.
