### ISSUE TITLE
Expand on range types changesets supports

### ISSUE THREAD

**Issue by Noviny** [atlassian/changesets#99]
Currently changesets supports `1.0.0`, `~1.0.0`, and `^1.0.0`, which is a subset of valid semver definitions.

@mitchellhamilton found the range types that yarn supports, and suggested we should do that.

So we need to: refind that info (I have lost the link he gave me soz)
Align our range type function with it.

**Comment by mitchellhamilton** [comment]
https://yarnpkg.com/lang/en/docs/cli/upgrade/#toc-yarn-upgrade-package-latest-l-caret-tilde-exact-pattern
